### ISSUE TITLE
empty requires table assumes host setuptools

### ISSUE THREAD

**Issue by gaborbernat** [pypa/build#102]
This is because ensurepip pulls in automatically setuptools, so that's auto-provisioned.

**Comment by FFY00** [comment]
As discussed in #106, we should create a semi-permanent environment to hold pip if needed. This would never invoke ensurepip on the build environment and install unwanted packages.

**Comment by FFY00** [comment]
Will be solved with #113.

**Comment by gaborbernat** [comment]
Fixed in #140
