### ISSUE TITLE
build uninstalls setuptools in a venv

### ISSUE THREAD

**Issue by henryiii** [pypa/build#109]
When you run from inside a venv (in my case, a venv inside conda), then `python -m build` *uninstalls setuptools* after running `python -m build`.

And then, on a second run, it immediately breaks, even with setuptools listed in the requires clause (assuming it is needed for ensurepip, perhaps?)

```fish
python3 -m venv venv
. venv/bin/activate.fish
python -m pip install build
python -m build
# setuptools is now gone
python -m build
ERROR Backend 'setuptools.build_meta' is not available
```

Probably closely related to #97 . I am in the same anaconda python3.7 env described in #108, only now with a "setuptools>=42" requirement.

**Comment by FFY00** [comment]
Yeah, sorry about that :confused:

Can you try #99 and see if it fixes it for you? I will come back to it this month and get it finally merged.

**Comment by gaborbernat** [comment]
This should no longer be the case with the new isolated build methods.
