### ISSUE TITLE
Speed up build isolation by providing pip externally in a semi-permanent environment

### ISSUE THREAD

**Issue by gaborbernat** [pypa/build#113]
Splitting out a comment made by by @FFY00 into it's own issue from https://github.com/FFY00/python-build/issues/106 as it's out of scope therem, but I think we should very much do this (at some point - not release blocker):

> I think the environment where we bootstrap pip into could actually be semi-permanent and shared between all builds. This would speed up isolated builds.

Strongly agree 👍

**Comment by FFY00** [comment]
The comment refers to using a separated semi-permanent environment for *pip*.

Reusing the build environment itself is something that could be explored but is not trivial. We need to ensure that only the expected packages are installed.

**Comment by gaborbernat** [comment]
We've done this via #140
