### ISSUE TITLE
PyPy2 isolation broken

### ISSUE THREAD

**Issue by gaborbernat** [pypa/build#120]
pypy does not handles/honor/cares about PYTHONHOME, see https://foss.heptapod.net/pypy/pypy/-/blob/branch/default/pypy/interpreter/app_main.py#L38, hence the issues here; prefixes remain under original executable path, which then pulls in the site-packages via https://foss.heptapod.net/pypy/pypy/-/blob/branch/default/lib-python/2.7/site.py#L295-297 and https://foss.heptapod.net/pypy/pypy/-/blob/branch/default/lib-python/2.7/distutils/sysconfig_pypy.py#L38-56 respectively

minimal reproducible:

```
env PYTHONHOME=this-is-missing pypy -E -m site
sys.path = [
    '/Users/bgabor8/git/github/python-build',
    '/Users/bgabor8/.pyenv/versions/pypy2.7-7.3.0/lib_pypy/__extensions__',
    '/Users/bgabor8/.pyenv/versions/pypy2.7-7.3.0/lib_pypy',
    '/Users/bgabor8/.pyenv/versions/pypy2.7-7.3.0/lib-python/2.7',
    '/Users/bgabor8/.pyenv/versions/pypy2.7-7.3.0/lib-python/2.7/lib-tk',
    '/Users/bgabor8/.pyenv/versions/pypy2.7-7.3.0/lib-python/2.7/plat-darwin',
    '/Users/bgabor8/.pyenv/versions/pypy2.7-7.3.0/lib-python/2.7/plat-mac',
    '/Users/bgabor8/.pyenv/versions/pypy2.7-7.3.0/lib-python/2.7/plat-mac/lib-scriptpackages',
    '/Users/bgabor8/.pyenv/versions/pypy2.7-7.3.0/site-packages',
]
USER_BASE: '/Users/bgabor8/.local' (exists)
USER_SITE: '/Users/bgabor8/.local/lib/pypy2.7/site-packages' (doesn't exist)
ENABLE_USER_SITE: True
```

vs

```
env PYTHONHOME=this-is-missing python2.7 -m site
ImportError: No module named site
```

**Comment by FFY00** [comment]
What do you propose to do? If `PYTHONHOME` is ignored how do virtual environments work there?

**Comment by gaborbernat** [comment]
> What do you propose to do? If `PYTHONHOME` is ignored how do virtual environments work there?

virtualenv never uses PYTHONHOME. Virtual environments work via copy/link files in the right positions, and then some shim site.py inject on Python 2. Personally I still propose to make virtualenv a dependency on Python 2, and delegate the job to it. Otherwise we can implement some copy/symlink+site.py rewrite here too...

**Comment by FFY00** [comment]
What about pulling virtualenv for PyPy2? I am not so happy about having 3 possible backends but I'd like to keep dependencies down.

**Comment by gaborbernat** [comment]
For reference virtualenv PyPy2 logic https://github.com/pypa/virtualenv/blob/main/src/virtualenv/create/via_global_ref/builtin/pypy/pypy2.py#L1. And yes, that could be the least effort solution while still keep some no-bootstrap issue 👍

**Comment by FFY00** [comment]
Okay. Do you want to work on it? It shouldn't be too hard but I don't have much time, or motivation TBH, to do it.

**Comment by gaborbernat** [comment]
If we pull in tox and then black+isort, then I'll do it.

**Comment by FFY00** [comment]
Not sure about black. black is very opinionated.

It expands things like this

```python
assert os.path.normcase(sysconfig.get_path(
    path,
    vars={
        'base': env.path,
        'platbase': env.path,
    }
)) in python_path
```

to

```python
assert (
    os.path.normcase(
        sysconfig.get_path(
            path,
            vars={
                'base': env.path,
                'platbase': env.path,
            },
        )
    )
    in python_path
)
```

Which I find much harder to read.

Can you do it with black locally and then use `git add -p` to select the only the relevant changes?

**Comment by gaborbernat** [comment]
IMHO black does here the reasonable thing, IMHO the code should be simplified to read better:

```
vars = {
   "base": env.path,
   "platbase": env.path,
}
path = os.path.normcase(sysconfig.get_path(path, vars=vars)
assert path in python_path
```

Much better, and is black friendly.

**Comment by FFY00** [comment]
The current code style is already pretty similar to black and moving to black results in a minimal patch, so I don't understand why you don't like most of the code right now.

Anyway, we can move to black.

> What would qualify as relevant change. Anything black touches is relevant, not?

The code you are touching.

**Comment by gaborbernat** [comment]
> The current code style is already pretty similar to black and moving to black results in a minimal patch, so I don't understand why you don't like most of the code right now.

The ``'`` part against ``"``... but I'll digress on it.
