### ISSUE TITLE
Simplify docs

### ISSUE THREAD

**Issue by gaborbernat** [pypa/build#131]
Currently one can generate/create the documentation by using the ``tox -e docs`` target. In light of this do we still need to keep around the non-cross platform method of ``python-build/docs/Makefile``? I'd propose we also move the docs one level up from source. Similar how virtualenv does this https://github.com/pypa/virtualenv/tree/main/docs

We should also remove many of trivial comments from within ``conf.py`` IMHO.

**Comment by FFY00** [comment]
I'd prefer to keep the makefile around, it prevents me from having to pull tox as a build dependency in a distro package.

https://github.com/archlinux/svntogit-community/blob/packages/python-build/trunk/PKGBUILD

Regarding the directory structure, I'd prefer to not mix up the documentation source and other files like `conf.py`. If there is a good reason to do this, I am not opposed.

**Comment by FFY00** [comment]
Eh, `make` can just be replaced with `sphinx-build -n -W docs/source` since we no longer need to call `sphinx-apidoc` and I think that is fair enough. We can remove the makefile.

With that in mind, we could move `docs/requirements.txt` to the root directory under `requirements-doc.tox` and proceed with the docs source one level up as yo propose.

**Comment by gaborbernat** [comment]
> Regarding the directory structure, I'd prefer to not mix up the documentation source and other files like `conf.py`. If there is a good reason to do this, I am not opposed.

But we already do at the moment within source folder you have both the documentation files and conf.py. At least we can bring it one level above.

> I'd prefer to keep the makefile around, it prevents me from having to pull tox as a build dependency in a distro package.

Why do you need to build the documentation in redistributing? Also how do you know how to invoke it at build time. At the moment we have doc build args specified both in tox.ini and makefile, so it's easy to get them out of sync.
