### ISSUE TITLE
We are relying on `get_requires_for_build_{sdist,wheel}` to be present

### ISSUE THREAD

**Issue by FFY00** [pypa/build#132]
In light of #130 I noticed we are wrongly relying on `get_requires_for_build_{sdist,wheel}`, optional hooks, to be present.

/me blames bad assumptions due to him being super distracted

**Comment by layday** [comment]
pep517 does not raise if these two hooks are undefined, it simply returns an empty list, so we shouldn't have to do anything special here.

**Comment by FFY00** [comment]
Ah, missed that when I revisited this. This behavior is controlled by `_allow_fallback`, which defaults to `True`, so we should be good.

**Comment by layday** [comment]
I believe `_allow_fallback` is only available for `prepare_metadata_for_build_wheel` - pep517 always falls back on `[]` for `get_requires_for_build_{sdist,wheel}`

**Comment by gaborbernat** [comment]
Ideally, we'd close this by adding a test to validate this assumption and make sure new versions of pep517 don't break it.
