### ISSUE TITLE
Curate output

### ISSUE THREAD

**Issue by FFY00** [pypa/build#142]
Right now we do not care much about the output. I wanted to pay a bit more attention to that.

I propose to keep the output limited to build backend output, this means swallowing the ensurepip output, and to curated messages from us (`build`). Our own messages should be clear that come from us, either by having an identifiable prefix or a specific style. Our messages should also be pretty limited, keeping the output clean. If we see need for debug messages we can offer that under a `--debug` flag.

For our messages, I propose adding a `build.print_info` method that could be overwritten, in `warnings.showwarning` fashion. The default implementation would use the `logging` module, but we would overwrite it in `__main__` to use a colorized raw print.

**Comment by pganssle** [comment]
It might be a good idea to be semi-consistent with `pip` and `tox` here, with different grades of verbosity? `-v`, `-vv` and `-vvv`

**Comment by FFY00** [comment]
Is `build` complex enough to warrant that? It is always something that could be expanded anyway.

**Comment by gaborbernat** [comment]
This project calls virtualenv on python 2 and pip everywhere, so if it's matching will be easy to forward flags to virtualenv and pip😎
