### ISSUE TITLE
Convert virtualenv from a mandatory dependency into an optional one.

### ISSUE THREAD

**Issue by KOLANICH** [pypa/build#147]
I don't use virtualenvs (even for the things for which using them may make sense, such as testing if a package installs and works on a clean system without any optional dependencies, I had a very negative experience with them, they are too large and extremily slow to create). Especially for building packages. So, probably, I shouldn't be forced to have this package on my machine.

**Comment by gaborbernat** [comment]
You can pass the --no-isolated flag to achieve this, so the feature already provided.

**Comment by FFY00** [comment]
virtualenv is only required for Python 2, which has been EOL for some time. But as Bernát said, you are free to remove it. I understand this is not an optimal solution but for the time being we'll have to put up with it :confused:
