### ISSUE TITLE
Commit structure

### ISSUE THREAD

**Issue by FFY00** [pypa/build#180]
Continuing from #169. We should adopt a commit format to make the history easier to read.

I propose the following:
- Commits should have descriptions, unless they are trivial
  - The description should have a quick summary of the issue or enhancement and a quick description of how it is being resolved. If it is a complex issue, we should have a quick description of the other approaches considered
  - If there are related issues or PRs, an effort should be made to reference them
- Commits should be prefixed by the part of the code they are changing.
  - The prefix should be chosen in reference to the logical root change -- the "interesting" change
    - eg. if I am changing some API in `build` and I update `build.env` to match, the `build` prefix should be used
  - Proposed prefixes:
    - `build`: `build` module
    - `env`: `build.env` module
    - `tests`: tests
    - `docs`: documentation
    - `readme`: REAME.md
    - `setup.py`: `setup.py`
    - `setup.cfg`: generic `setup.cfg` settings (tools have their own prefix)
    - `pyproject`: generic `pyproject.toml` settings (tools have their own prefix)
    - `pre-commit`: `.pre-commit-config.yaml` and other pre-commit related files
    - `black`: black settings
    - `mypy`: mypy settings
    - `flake8`: flake8 settings or comments (eg. `noqa`)
    - `isort`: isort settings or comments (eg. `isort:*`)
    - `coverage`: coverage settings or comments (eg. `pragama: no cover`)
    - `tox`: `tox.ini` and related
    - `rtd`: `.readthedocs.yaml` and related
    - `ci`: `.github/workflows/*` and related
    (etc... I think you get the idea)

These do not need to be hard rules, just guidelines.

Looking at https://github.com/pypa/build/pulls?q=is%3Apr+sort%3Aupdated-desc+is%3Aclosed, I do not think we need to adopt an automated system to check this. But if we start to get more user contributions, we should consider it. As long as we are only getting occasional contributions, I am fine asking the users directly (which is also a better experience than an automated bot :stuck_out_tongue:).

**Comment by layday** [comment]
These all sound like reasonable guidelines to me and with the exception of the prefixes they are things seasoned FOSS devs will have internalised anyway (not that I consider myself to be one ;).

**Comment by FFY00** [comment]
I am going to close this as there didn't seem to be any opposition.
This issue can be used as a reference until we write up some contribution guidelines.

**Comment by gaborbernat** [comment]
My only comment to this is that hard to judge when you touch multiple for a given feature and even harder to police. I don't have anything against it, but it's unlikely I'll follow it unless it can be automated, and I'm not expecting our contributors to do either. In case you're happy to manage this on your own, feel free to go ahead with it, but also be mindful not to make yourself a bus factor from the POV of this project.
