### ISSUE TITLE
Rename `ProjectBuilder.get_dependencies`

### ISSUE THREAD

**Issue by layday** [pypa/build#182]
Reading https://github.com/pypa/build/issues/181#issuecomment-721579088, I think this method's name is ambiguous and should be renamed to e.g. `get_backend_dependencies`.  Would there be any objections?

**Comment by gaborbernat** [comment]
IMHO:
- https://github.com/pypa/build/blob/5d3f89b6f75086b6280d97c68c6d0149bdc6c7e7/src/build/__init__.py#L184 should be `get_requires,`
- https://github.com/pypa/build/blob/5d3f89b6f75086b6280d97c68c6d0149bdc6c7e7/src/build/__init__.py#L192 should be `get_requires_for_build`.

I agree the current naming is very unfortunate and misleading.

**Comment by FFY00** [comment]
Well, it is in a class named `ProjectBuilder`, which purpose is to build the project, I find `get_dependencies` to be an acceptable name.

My comment there however was wrong, sorry. I should have referred to them as build system dependencies and project build dependencies.

We can rename the methods, but I think @gaborbernat names are still ambiguous. IMO, it should be `build-system-dependencies` and `get_build_dependencies`.

**Comment by layday** [comment]
The issue that I see is that `get_dependencies` can be confused with the dependencies from `build-system` or might be assumed to return both the dependencies provided by the backend and the dependencies declared in `pyproject.toml`- not so much that that it might be confused with runtime dependencies.

**Comment by gaborbernat** [comment]
I agree with @layday.
