### ISSUE TITLE
Dependencies from `get_requires_for_build_sdist` are not installed in isolated environment

### ISSUE THREAD

**Issue by Carreau** [pypa/build#194]
It seem the with the latest version of build; setuptools-scm decides that my project version is always 0.0.0; is that expected ? I found other issues mentioning setutools-scm, but it seem more targeted toward adopting setuptools-scm for build itself. Anly pointer on how to fix this beyond not using 0.1 ? 

See https://github.com/zarr-developers/zarr-python/pull/666

**Comment by layday** [comment]
This isn't an issue with `build`; you haven't added `setuptools-scm` to your `pyproject.toml` requires.  I presume because setuptools is invoked through PEP 517 it does not honour `setup_requires`.

**Comment by gaborbernat** [comment]
Yeah, you actually need to specify your build dependencies in pyproject.toml.

What you have https://github.com/zarr-developers/zarr-python/blob/master/pyproject.toml#L2, and what you should https://github.com/pypa/virtualenv/blob/main/pyproject.toml#L5

`setup_requires` is deprecated and has been for a long time now.

**Comment by layday** [comment]
Upon closer inspection `setuptools` should return its `setup_requires` from `get_requires_for_build_x`.  Are we not installing the dependencies from `get_requires` before builing a distribution in an isolated environment?

**Comment by layday** [comment]
I'm reopening this because it seems like a legitimate issue with isolated builds.  Acorrding to PEP 517:

> The `build_sdist` hook is executed in an environment which contains the bootstrap requirements from `pyproject.toml` and those specified by the `get_requires_for_build_sdist` hook.

We'll probably want to install these after the `build_dependencies` in `_build_in_isolated_env`:

https://github.com/pypa/build/blob/b39dcddb6c7e822398c49b81d73fcbcdedea607b/src/build/__main__.py#L53

Thanks for reporting, @Carreau.

**Comment by FFY00** [comment]
Fixed in 260c51800dc4df0fff7e522bff7bba9d975a0bcb.
