### ISSUE TITLE
ProjectBuilder.build does not return the wheel filename

### ISSUE THREAD

**Issue by pfmoore** [pypa/build#209]
The documentation says that `ProjectBuilder.build` returns the wheel filename, but it currently does not.

**Comment by layday** [comment]
There hasn’t been a release with this change. Does RTD default to displaying the doc for master? Can we change that?

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by pfmoore** [comment]
Ah, it didn't occur to me that the docs were showing master. Sorry, I should have checked. I don't know if there is a way to get RTD to show the latest release docs by default, sorry. (I just checked pip's RTD page, and there is a "default version" set to "stable", but I don't know how to set that 🙁)

**Comment by uranusjr** [comment]
RTD has a “stable” version that points to the latest released version, while “latest” points to master. So it’s probably best to set the default to stable instead (and change the link in both README and the repo description).

**Comment by gaborbernat** [comment]
I think only @FFY00 has admin rights on the build.

**Comment by layday** [comment]
"Stable" is a bit of a misnomer but I don't think we can change the labels.

**Comment by FFY00** [comment]
I changed the link in the repo description and the default RTD version to stable.

**Comment by pfmoore** [comment]
Thanks. FWIW, I switched my script to use the CLI instead, for the short term (it's just as easy to use in practice - actually a bit easier as I can use the standard subprocess API to capture and hide backend output). So this isn't a significant blocker for me.

**Comment by gaborbernat** [comment]
Resolves as per above of @FFY00
