### ISSUE TITLE
Failure to build if ensurepip isn't available

### ISSUE THREAD

**Issue by EpicWink** [pypa/build#224]
On my Ubuntu system I use `virtualenv` to handle my virtual environments, and don't have the `python3-venv` package installed. `build` v0.2.0 now tries to run `ensurepip`, but this results in an error:

```
The virtual environment was not created successfully because ensurepip is not
available.  On Debian/Ubuntu systems, you need to install the python3-venv
package using the following command.

    apt-get install python3-venv

You may need to use sudo with that command.  After installing the python3-venv
package, recreate your virtual environment.

Failing command: ['/tmp/build-env-6ejv4upq/bin/python3', '-Im', 'ensurepip', '--upgrade', '--default-pip']
```

Introduced in a0802bb. I suspect this was caused by changing `with_pip=False` to `with_pip=True` in [the instantiation of `venv.EnvBuilder`](https://github.com/pypa/build/blob/a0802bb31d810acc58094c766745430107be6345/src/build/env.py#L171) in `_create_isolated_env_venv`. A current workaround is to install `virtualenv` in my virtual environment

**Comment by uranusjr** [comment]
This is a very long known issue, and ultimately Debian is the one to blame. https://gist.github.com/tiran/2dec9e03c6f901814f6d1e8dad09528e

If pipx wants to be as user-friendly as possible, it can probably detect `ensurepip` is available before creating the environment, and either

1. Show an error telling the user to install `python3-venv` or `virtualenv`.
2. Continue with the in-environment pip and not making the executables available in `PATH` (with an warning about consequences).

But again, this is ultimately a Debian issue, and I’ll be fully supportive if the resolution is to do nothing and tell the user to yell at Debian devs instead. Nobody needs to clean up Debian’s mess but Debian maintainers.

**Comment by gaborbernat** [comment]
> A current workaround is to install `virtualenv` in my virtual environment

Your options are either to install venv vi apt-get or to install build with the extra virtualenv (https://github.com/pypa/build/blob/master/setup.cfg#L59-L60). 

This is by design.
