### ISSUE TITLE
bug: fails on GHA's default pipx

### ISSUE THREAD

**Issue by henryiii** [pypa/build#226]
This has suddenly started failing on GitHub Actions, using pipx. It seems to be trying to use `--no-warn-script-location` when such an option does not exist.

```
Run pipx run --spec build pyproject-build
Uninstalling setuptools-39.0.1:
  Successfully uninstalled setuptools-39.0.1
25l25h
Usage:   
  /tmp/build-env-4hxt_nra/bin/python -m pip install [options] <requirement specifier> [package-index-options] ...
  /tmp/build-env-4hxt_nra/bin/python -m pip install [options] -r <requirements file> [package-index-options] ...
  /tmp/build-env-4hxt_nra/bin/python -m pip install [options] [-e] <vcs project url> ...
  /tmp/build-env-4hxt_nra/bin/python -m pip install [options] [-e] <local project path> ...
  /tmp/build-env-4hxt_nra/bin/python -m pip install [options] <archive url/path> ...

no such option: --no-warn-script-location
Traceback (most recent call last):
  File "/opt/pipx/.cache/a354a1c2584f35b/bin/pyproject-build", line 8, in <module>
    sys.exit(entrypoint())
  File "/opt/pipx/.cache/a354a1c2584f35b/lib/python3.6/site-packages/build/__main__.py", line 209, in entrypoint
    main(sys.argv[1:])
  File "/opt/pipx/.cache/a354a1c2584f35b/lib/python3.6/site-packages/build/__main__.py", line 205, in main
    build_package(args.srcdir, outdir, distributions, config_settings, not args.no_isolation, args.skip_dependencies)
  File "/opt/pipx/.cache/a354a1c2584f35b/lib/python3.6/site-packages/build/__main__.py", line 94, in build_package
    _build_in_isolated_env(builder, outdir, distributions, config_settings)
  File "/opt/pipx/.cache/a354a1c2584f35b/lib/python3.6/site-packages/build/__main__.py", line 56, in _build_in_isolated_env
    env.install(builder.build_dependencies)
  File "/opt/pipx/.cache/a354a1c2584f35b/lib/python3.6/site-packages/build/env.py", line 142, in install
    subprocess.check_call(cmd)
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/tmp/build-env-4hxt_nra/bin/python', '-Im', 'pip', 'install', '--no-warn-script-location', '-r', '/tmp/build-reqs-paf79l14.txt']' returned non-zero exit status 2.
```

This will start breaking about a dozen libraries for me. :'( And anyone following the Scikit-HEP guides: https://scikit-hep.org/developer/gha_pure#distribution-pure-python-wheels

**Comment by layday** [comment]
I assume your version of Python 3.6 comes with pip < 10.0; `--no-warn-script-location` was added in [10.0](https://github.com/pypa/pip/commit/fc7ca264892767454b166d0fc001a6ca95bde22e).  If 3.7.0 was released with 10.0 or greater, we might be able to trivially extend the version check on line 174 of `env.py`:

https://github.com/pypa/build/blob/0da5d5c3d55fb6142e47e95821c9471c5b5345ca/src/build/env.py#L174

**Comment by henryiii** [comment]
Yes, that is correct. I recently compiled pip versions and Python support here: https://github.com/joerick/cibuildwheel/discussions/580#discussioncomment-346776

**Comment by layday** [comment]
Python 3.7.0 has pip 10.0.1: https://github.com/python/cpython/tree/v3.7.0/Lib/ensurepip/_bundled; 3.6.0-3.6.5 have pip 9.0: https://github.com/python/cpython/tree/v3.6.5/Lib/ensurepip/_bundled.

**Comment by henryiii** [comment]
Excellent, that's useful information (and a good idea for a place to check). So 3.6 often does come with 9.

**Comment by uranusjr** [comment]
It may be worthwhile for pipx to switch to using the `PIP_NO_WARN_SCRIPT_LOCATION` environ as well. That won’t fail if the pip installation does not recognise it (and those versions won’t warn about PATH anyway).

**Comment by gaborbernat** [comment]
@uranusjr see the PR, I think the conclusion was that we're better of updating the user to pip 10+, mostly because pip 9 has issues with wheel compatibility, python-requires handling, etc.

**Comment by uranusjr** [comment]
Always requiring pip 10+ makes sense as well, pip 9 is problematic in many aspects anyway.
