### ISSUE TITLE
Source archive format

### ISSUE THREAD

**Issue by thmo** [pypa/build#243]
I have this in my `setup.cfg`:
```
[sdist]
formats = bztar zip
```
This used to work with `python ./setup.py sdist` and created a `.tar.bz` as well as `.zip` archive in `dist/`.

Now, moving to `python -m build`, only a `.tar.gz` is created in `dist/`.

Is there a way to influence the source archive formats?

**Comment by FFY00** [comment]
I don't think PEP 517 allows you to generate .zip sdists. You should not be using anything other than .tar.gz anyway.

But this is an implementation detail of setuptools, pypa/build just calls the backend.

**Comment by thmo** [comment]
But shouldn't the still existing `[sdist]` section in `setup.cfg` still work then? Or do I confuse something?

**Comment by FFY00** [comment]
No because the PEP 517 `build_sdist` hook explicitly says it should return a .tar.gz. There is no way to build any other kind of sdist with PEP 517.

**Comment by thmo** [comment]
Ok, thanks for the clarification.
