### ISSUE TITLE
pip.conf not used / default system pip used / not upgraded

### ISSUE THREAD

**Issue by gst** [pypa/build#246]
Hi, having :

```
06:09 $ pip list
Package    Version
---------- -------
build      0.3.0
packaging  20.9
pep517     0.9.1
pip        21.0.1
pyparsing  2.4.7
setuptools 51.3.3
toml       0.10.2
wheel      0.36.2

06:09 $ python -V
Python 3.8.5

06:09 $ cat pyproject.toml 
[build-system]
requires = ["setuptools>=40.1.0", "wheel", "toml", "axsetuptools"]
build-backend = "setuptools.build_meta"
```

I see that my /etc/pip.conf is not honored / taken into account to download build dependencies (which are in pyproject.toml).

I expected it to be used ..

EDIT:

it's because the "stock" pip version of ubuntu is used.. and that version appears to be 20.0.2 : 

```
pip 20.0.2 from /usr/lib/python3/dist-packages/pip (python 3.8)
```

So the issue is that _build_ does not upgrade pip prior to installing the dependencies..

**Comment by FFY00** [comment]
What exactly is happening?

Please note that pypa/build usage of pip is merely an implementation detail, so don't expect the behavior to be modified by any external thing.

**Comment by gst** [comment]
Well as said: my /etc/pip.conf, which contains/declares a private pypi server, is apparently not used by `build`.

when I use `build` with the above configuration I get : 

```bash
07:04 $ python -m build -w
Found existing installation: setuptools 44.0.0
Uninstalling setuptools-44.0.0:
  Successfully uninstalled setuptools-44.0.0
Collecting toml
  Using cached toml-0.10.2-py2.py3-none-any.whl (16 kB)
ERROR: Could not find a version that satisfies the requirement axsetuptools (from -r /tmp/build-reqs-pb3ox7y5.txt (line 2)) (from versions: none)
ERROR: No matching distribution found for axsetuptools (from -r /tmp/build-reqs-pb3ox7y5.txt (line 2))
```

while my pypi server definitively has that build dependency available : 

```bash
07:04 $ pip search axsetuptools
axsetuptools (0.0.0.15)  - [root/ax-focal] Algolux python setup tools
```

**Comment by gst** [comment]
you mean `build` doesnt use `pip` to install build dependencies ??

**Comment by gaborbernat** [comment]
> you mean `build` doesn't use `pip` to install build dependencies ??

He means it's an implementation detail, and we'd be free to change to other tools. At the moment, however, we do use pip, see https://github.com/pypa/build/blob/main/src/build/__main__.py#L56-L58

The fact that ``/etc/pip.conf`` is not picked up should be though a pip bug unless one of our flags we pass in (see above) stops from pip using it.

**Comment by gst** [comment]
Hi, thanks.

But/So I actually strace'd build and I see internally it uses the **system** installed pip directly somehow.

which in my case appears to be 20.0.2 : 

```bash
07:26 $ /usr/bin/python3 -m pip --version
pip 20.0.2 from /usr/lib/python3/dist-packages/pip (python 3.8)
```
but this one is quite buggy/doesnt handle /etc/pip.conf at all.

Now. more on this : I just upgraded it latest pip version:

```
07:30 $ /usr/bin/python3 -Em pip --version
pip 21.0.1 from /usr/local/lib/python3.8/dist-packages/pip (python 3.8)
```

and yet I get the exact same issue : internally I see when I strace build that it uses pip 20.0.2 ..  which is the trouble..

**Comment by gaborbernat** [comment]
Can you install this repository into a virtual environment, edit https://github.com/pypa/build/blob/main/src/build/env.py#L168 to print out the command called, and report back here with that?

**Comment by gst** [comment]
here it is: 

===> ['/tmp/build-env-us2ji2s8/bin/python', '-Im', 'pip', 'install', '--use-pep517', '--no-warn-script-location', '-r', '/tmp/build-reqs-65yarh_9.txt']

```
07:35 $ strace -o strace python -m build -w 
Found existing installation: setuptools 44.0.0
Uninstalling setuptools-44.0.0:
  Successfully uninstalled setuptools-44.0.0
===> ['/tmp/build-env-us2ji2s8/bin/python', '-Im', 'pip', 'install', '--use-pep517', '--no-warn-script-location', '-r', '/tmp/build-reqs-65yarh_9.txt']
Collecting setuptools>=40.1.0
  Using cached setuptools-54.0.0-py3-none-any.whl (784 kB)
Collecting toml
  Using cached toml-0.10.2-py2.py3-none-any.whl (16 kB)
Collecting wheel
  Using cached wheel-0.36.2-py2.py3-none-any.whl (35 kB)
ERROR: Could not find a version that satisfies the requirement axsetuptools (from -r /tmp/build-reqs-65yarh_9.txt (line 4)) (from versions: none)
ERROR: No matching distribution found for axsetuptools (from -r /tmp/build-reqs-65yarh_9.txt (line 4))
```

**Comment by gaborbernat** [comment]
Can you inject there a ``'/tmp/build-env-us2ji2s8/bin/python', '-Im', 'pip', 'list'`` and ``'/tmp/build-env-us2ji2s8/bin/python', '-Im', 'pip', '--version'`` calls in there?

**Comment by gst** [comment]
pip --version gives: pip 20.0.2 from /tmp/build-env-c9hix7zp/lib/python3.8/site-packages/pip (python 3.8)

pip --list gives : 

```
Package       Version  
------------- ---------
axcamera      0.3.0.102
pip           20.0.2   
pkg-resources 0.0.0    
```

strange.. that 0.0.0 and that pip 20.02.. because I dont see any left traces of it on my system..

**Comment by layday** [comment]
build uses ensurepip which, unless it has been patched by your distro, will install the version of pip which comes bundled with your version of Python.  If you are a Debian or Ubuntu user, this will instead be the version of pip that you have installed with apt.  This is the same as if you were to create a virtual environment with venv (`python -m venv venv`) - observe that it has pip 20.0.2.

**Comment by gst** [comment]
ok.. this is quite unfortunate then.. :/ 

wouldn't it make sense to update pip itself inside the first venv/virtualenv created by _build_, prior to try to build ?

**Comment by gst** [comment]
NB: I'm effectively on ubuntu ( 20.04 ).

**Comment by gaborbernat** [comment]
Ah, venv is notoriously broken on there with the pip devendoring. You can install the virtualenv extra to work around this: ``build[virtualenv]``.

**Comment by FFY00** [comment]
Well, I don't think there's that much point trying to make pip pick up the private repository. As I said, pip is an implementation detail and so configuring pip to use a private server is also an implementation detail, and may break anytime. We need to come up with a way to include extra repositories in pypa/build that is not pip specific. Optimally, this would be a standard configuration file that could be used by all the packaging tools.

**Comment by gaborbernat** [comment]
> Well, I don't think there's that much point trying to make pip pick up the private repository.

IMHO it solves the immediate problem until we agree with the second part, which might take a while.

**Comment by layday** [comment]
> wouldn't it make sense to update pip itself inside the first venv/virtualenv created by _build_, prior to try to build ?

We do do that but not for versions as recent as 20.0.2 - we were not aware that there was an issue with `pip.conf`.  Would you be able to locate the issue on the pip tracker?

**Comment by gst** [comment]
> Would you be able to locate the issue on the pip tracker?

douh.. I can try to. give a shot. but pip tracker is quite.. huge.. :\

**Comment by gst** [comment]
ah.. a workaround (the pip 20.0.2 issue itself) is to : 

```bash
export PIP_CONFIG_FILE=/etc/pip.conf 
python -m build ...
```
```
07:41 $ PIP_CONFIG_FILE=/etc/pip.conf python -m build -w 
Found existing installation: setuptools 44.0.0
Uninstalling setuptools-44.0.0:
  Successfully uninstalled setuptools-44.0.0
Package       Version  
------------- ---------
axcamera      0.3.0.102
pip           20.0.2   
pkg-resources 0.0.0    
===> ['/tmp/build-env-6dv2w3i3/bin/python', '-Im', 'pip', 'install', '--use-pep517', '--no-warn-script-location', '-r', '/tmp/build-reqs-i1s1unce.txt']
Looking in indexes: http://pypi:3141/root/ax-focal/+simple/
Collecting setuptools>=40.1.0
  Downloading http://pypi:3141/root/pypi/%2Bf/d85/b57c41e88b69a/setuptools-54.0.0-py3-none-any.whl (784 kB)
     |████████████████████████████████| 784 kB 1.9 MB/s 
Collecting toml
  Downloading http://pypi:3141/root/pypi/%2Bf/806/143ae5bfb6a3c/toml-0.10.2-py2.py3-none-any.whl (16 kB)
Collecting axsetuptools
  Downloading http://pypi:3141/root/ax-focal/%2Bf/374/918bcaa228c8f/axsetuptools-0.0.0.15-py3-none-any.whl (4.7 kB)
Collecting wheel
  Downloading http://pypi:3141/root/pypi/%2Bf/78b/5b185f0e5763c/wheel-0.36.2-py2.py3-none-any.whl (35 kB)
Collecting cython
  Downloading http://pypi:3141/root/pypi/%2Bf/b53/c9d7b545c70f4/Cython-0.29.22-cp38-cp38-manylinux1_x86_64.whl (1.9 MB)
     |████████████████████████████████| 1.9 MB 3.3 MB/s 
Installing collected packages: setuptools, toml, cython, axsetuptools, wheel
Successfully installed axsetuptools-0.0.0.15 cython-0.29.22 setuptools-54.0.0 toml-0.10.2 wheel-0.36.2
```

**Comment by gst** [comment]
I dont find any specific (closed) issue in pip tracker. 

But the issue is definitively solved in recent/latest version of pip (21.0.1 atm). So my question still remains : 

why not upgrade pip itself in the first created venv/virtualenv prior to do the build itself ? :/

**Comment by gaborbernat** [comment]
> why not upgrade pip itself in the first created venv/virtualenv prior to do the build itself ? :/

Because that involves a network call that potentially can fail (and definitely slows down) the process. And unless you're in some extreme case you don't need it. If anything we could add a ``--upgrade-pip`` flag but as @FFY00 said we don't want to expose pip under the hood... so perhaps a _BUILD_PIP_UPGRADE env var could be the middle ground.

**Comment by gst** [comment]
hmm I see. well personally I'm using the PIP_CONFIG_FILE to workaround the issue in my case.

not sure what can be done to/with this issue then..

**Comment by gst** [comment]
I'm still thinking this has some value to upgrade pip itself prior to actually install the build dependencies. The value of fixing such kind of trouble basically.. and there can be others kind for sure IMO that would/could be solved by this pre-update.. still IMHO..

**Comment by layday** [comment]
The more obscure an issue is and the more easily rectifiable by the user the issue is the more I would lean towards not upgrading pip by default.  However, I'm not convinced that using pip should be considered an implementation detail.

**Comment by gst** [comment]
well yes build could allow to upgrade pip in the created virtual env.. then.

**Comment by layday** [comment]
I'd like to know more about what is causing this issue.

Does `python -m pip install axsetuptools` in a fresh venv work?  If it doesn't, does it work after upgrading pip in the venv: `python -m pip install -U pip && python -m pip install axsetuptools`? If it does, does it also work after downgrading pip: `python -m pip uninstall -y axsetuptools && python -m pip install -U pip==20.0.2 && python -m pip install axsetuptools`?

**Comment by gst** [comment]
> python -m pip install axsetuptools

works. If-and-only-if with a pip version not having the issue of not reading its configuration file. obviously.

**Comment by layday** [comment]
So it doesn't work after downgrading or did you not attempt it?

**Comment by gst** [comment]
I know it does not work with pip 20.0.2 because that version of pip is buggy and doesnt read its /etc/pip.conf configuration file : 

```
11:49 $ /usr/bin/python3 -m pip install -v axsetuptools
User install by explicit request
Created temporary directory: /tmp/pip-ephem-wheel-cache-e0k_rl3u
Created temporary directory: /tmp/pip-req-tracker-e84w2e9n
Initialized build tracking at /tmp/pip-req-tracker-e84w2e9n
Created build tracker: /tmp/pip-req-tracker-e84w2e9n
Entered build tracker: /tmp/pip-req-tracker-e84w2e9n
Created temporary directory: /tmp/pip-install-xhu22dw3
1 location(s) to search for versions of axsetuptools:
* https://pypi.org/simple/axsetuptools/
```

as you can see that pip version uses the regular pypi.org server. while I have another one defined in my /etc/pip.conf.

```
11:49 $ /usr/bin/python3 -m pip --version
pip 20.0.2 from /usr/lib/python3/dist-packages/pip (python 3.8)
```

**Comment by layday** [comment]
I wanted to see if it was pip that was buggy in general or if it was the system pip that was buggy.  Debian apply a number of patches to both pip and venv.

**Comment by gst** [comment]
I'm open to make a patch/MR to add an option to allow to upgrade pip itself inside the first created _env_, prior to install the true build dependencies.. I'd name it `--upgrade` basically

is there someone to approve ?

but I'm still actually inclined to say that the default should be to upgrade. but still allow to no upgrade with an option/argument so. The pros are better than the cons to me. (fix such kind of _annoying_ trouble).

any comment ?

**Comment by uranusjr** [comment]
I think the issue should be solved more fundamentally. Currently `build` allows building the isolated environment with `venv` or `virtualenv` (the latter already solves the upgrading issue to an extent). The mechanism should likely be extended into a plugin protocol to allow populating environments using anything the user wants, potentially not even using pip. A user can freely choose to use a environment backend that does upgrade pip inside if they wish.

**Comment by gst** [comment]
> The mechanism should likely be extended into a plugin protocol to allow populating environments using anything the user wants, potentially not even using pip. A user can freely choose to use a environment backend that does upgrade pip inside if they wish.

this is a whole other story :/

**Comment by uranusjr** [comment]
It is, because the whole feature request involves something that does not match your own mental model (which is not anyone’s fault, some things are just made differently). It’s kind of like asking a restaurant to use a particular blend of beef for your burger. There are zero technical difficulties to fulfill the request; it’s a perfectly valid bussiness model for your own burger place. But that’s just not the abstraction layer this shop works on, we need to create a new burger on the menu for you to choose from instead.

**Comment by layday** [comment]
This particular issue should be reported to Ubuntu as it does not occur with stock pip:

```sh
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal
$ python3 -V
Python 3.8.5
$ python3 -m venv venv
$ source venv/bin/activate
(venv) $ cat /etc/pip.conf 
[install]
user = true
(venv) $ pip config list
(venv) $ pip list
Package       Version
------------- -------
pip           20.0.2 
pkg-resources 0.0.0  
setuptools    44.0.0 
(venv) $ pip install --force-reinstall pip==20.0.2
Collecting pip==20.0.2
  Using cached pip-20.0.2-py2.py3-none-any.whl (1.4 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 20.0.2
    Uninstalling pip-20.0.2:
      Successfully uninstalled pip-20.0.2
Successfully installed pip-20.0.2
(venv) $ pip config list
install.user='true'
```

**Comment by gst** [comment]
@layday 

well. that could be.. but I still believe that `build` should allow to upgrade pip itself in the freshly created virtual env. prior to install the dependencies.. and eventually should do(or at least try to) it by default.

So I keep this issue open..

**Comment by henryiii** [comment]
If an exact version of pip was buggy, we could update if that version was detected. But it’s not a pip problem, it’s a vendored pip problem. Ubuntu does horrible things to pip. Ubuntu 18.04 bundles pip 9, even if you have python-38 installed!

Build updates pip in the venv before doing anything else if it’s older than 19.1. Newer than that should work, so it’s pointless to waste time and network updating it. Have you opened the issue with Ubuntu? Given it is just their buggy bundle and not official pip 20.02 that’s broken.

**Comment by gst** [comment]
Hi, well. 

maybe but what if tomorrow another system which bundles another version of pip is also broken.. the same problem would arise : and here I simply propose a general solution/fix and/or feature .. basically, at `build` level itself.

I'm sure it would be welcome by other users too.

**Comment by layday** [comment]
As has been mentioned before, you are able to use virtualenv which is both faster and its bundled copy of pip receives regular updates.  I would consider this a 'general solution/fix and/or feature' at the level of build.

**Comment by gst** [comment]
I'm not sure to what your refer @layday ..

**Comment by layday** [comment]
If you install virtualenv or build with the virtualenv extra (`build[virtualenv]`(, build will use virtualenv in preference to venv.  venv is the standard library module (unbundled by Debian) and virtualenv is a third-party package, maintained by the PyPA.

**Comment by henryiii** [comment]
It will also be faster :)

**Comment by gst** [comment]
Hi,

ok I'll take the solution to use build[virtualenv] for now :)

thx.
