### ISSUE TITLE
check_version does not verify extras

### ISSUE THREAD

**Issue by eli-schwartz** [pypa/build#25]
https://github.com/FFY00/python-build/blob/360966b687c15d8357ba98f9e194ff0f877ce3f2/build/__init__.py#L62-L64

This doesn't do what it looks like it does. metadata.get_all merely checks to see if the project's PKG-INFO declares that such an extra exists. It doesn't check to see if the extra is enabled due to having all the required dependencies.

Instead, distribution(''....').requires should be used to recursively retrieve dependencies one level deeper, and all dependencies which are associated with the desired extra should be checked as well.

**Comment by layday** [comment]
We don't check transitive dependencies at all, do we?  Extras just specify more dependencies that we don't check - the main issue is that `check_version` does not verify dependencies of declared build dependencies, though exras pose a problem in themselves.
