### ISSUE TITLE
CI flake: pip update may not do anything

### ISSUE THREAD

**Issue by henryiii** [pypa/build#256]
Probably should add a test forcing the exact minimum supported pip. The pip changelog is terrible about not having the details of when things get added or removed (try to find when eggs were dropped, for example).

—-

I believe this requires Pip 19.something (0 or 1), we need to bump the minimum check. It’s currently breaking our CI (macOS Python 3.6 has 18.something which is missing this flag).

_Originally posted by @henryiii in https://github.com/pypa/build/issues/232#issuecomment-794832786_

**Comment by layday** [comment]
I thought we already require 19.1 as a minimum.  Do you have a link to the CI output?

**Comment by henryiii** [comment]
That’s weird, we do. At least I we try to. It’s the most recent build.

https://github.com/pypa/build/runs/2068846663?check_suite_focus=true

```

Requirement already up-to-date: pip in /private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/build-env-zd7okh36/lib/python3.6/site-packages (18.1)
438
Uninstalling setuptools-40.6.2:
439
  Successfully uninstalled setuptools-40.6.2
```

**Comment by henryiii** [comment]
Note that is trying to update, I think, but printing out that it is already up to date at version 18.1. (On a phone, so a little hard to debug).  Would requiring a modern version in the update command help (would it ever not update without it?)? If we manually update, we should be at 20.3.4+.

**Comment by layday** [comment]
This is probably a flake or it would've popped up in CI before today.

**Comment by gaborbernat** [comment]
Note we can use virtualenv to create an environment with the exact pip version and run the test it those.

**Comment by henryiii** [comment]
Pretty sure the issue is that when PyPI can't be reached, "upgrade" simply does nothing.
