### ISSUE TITLE
Is it possible to control compression for wheels built with the help of `build` frontend?

### ISSUE THREAD

**Issue by KOLANICH** [pypa/build#258]
I'd like to be able to create wheels without compression - I'll still will install them on the same machine using pip after that. I have tried `-C--compression=stored` without any success.  `python3 ./setup.py bdist_wheel --compression=stored` worked as intended.

I am not wery sure whoose bug it is, setuptool's, or wheel's, but there are other build backends, and, so to control what compression is used, an interface at least is needed.

**Comment by gaborbernat** [comment]
This is not possible per packaging standards python adopted. The pep 517 clearly states both sdist and wheel must be compressed via tar.gz and zip format respectively.

**Comment by KOLANICH** [comment]
It doesn't say anything about compression within wheels.

**Comment by gaborbernat** [comment]
Because that's already defined as zip within the earlier https://www.python.org/dev/peps/pep-0427/#abstract

**Comment by layday** [comment]
They are asking if they can change the compression level - not the format.  You _can_ do this with `python -m build -w -C--global-option=--compression -C--global-option=stored` but the fact that it works is a bit of an accident.

**Comment by KOLANICH** [comment]
@layday, thank you. that works (for setuptools-based projects). -C "--global-option=--compression=stored" though doesn't, and it is a bug in setuptools, that worths fixing.

@gaborbernat, it still would make sense to define a single interface  to control compression in wheels in all backends. The easiest to implement way is, of course, an env variable read from `wheel` directly, so jo support in third-party tools is needed, but I don't think it is the correct way.

**Comment by layday** [comment]
Flit and Poetry don't even use the wheel package - there is no path to adding a generic wheel compression option.

> @layday, thank you. that works (for setuptools-based projects). -C "--global-option=--compression=stored" though doesn't, and it is a bug in setuptools, that worths fixing.

* https://github.com/pypa/setuptools/issues/2491
* https://github.com/pypa/setuptools/issues/2528
