### ISSUE TITLE
Potentially sensitive path information contained in sdist tar.gz

### ISSUE THREAD

**Issue by richardsheridan** [pypa/build#269]
The full absolute path of the uncompressed tarball in it's temporary folder is recorded when creating the final gzipped artifact. This can often contain a username or other potentially private directory structure information. A relative path should be used, or possibly something equivalent to `gzip --no-name`. The tarball itself uses an appropriate relative path.

This was observed on build 0.3.0 on Win10/CPython 3.8.5.

**Comment by uranusjr** [comment]
This is actually a Python bug and not fixable by this project. See https://bugs.python.org/issue41316

**Comment by richardsheridan** [comment]
Apparently the backported fix is available in CPython 3.8.8.

**Comment by layday** [comment]
See also https://github.com/pypa/build/issues/255.

**Comment by Ark-kun** [comment]
Strangely, for me `python setup.py sdist` was producing clean archives while `python -m build` produces problematic archives. Perhaps the python versions were different...
