### ISSUE TITLE
Cannot create venv _without_ symlinks using Command Line Tools build of Python on macOS

### ISSUE THREAD

**Issue by layday** [pypa/build#271]
See https://bugs.python.org/issue38705.  This seems to have bitten some users lately:

* https://github.com/pypa/packaging-problems/issues/493
* https://github.com/pypa/packaging-problems/issues/488

Note that the venv CLI defaults to using symlinks on platforms other than Windows so we could do the same in build.  We could otherwise discourage build users from relying on the macOS-provided Python.

**Comment by henryiii** [comment]
Using symlinks on Unix and following the default behavior of `python -m venv <name>` seems quite reasonable. Also saves a little space if anyone cares about a temporary venv. :)

**Comment by gaborbernat** [comment]
Does the issue also happen with virtualenv? Using virtualenv in these cases might also be a good workaround.

**Comment by henryiii** [comment]
That's the workaround we have been suggesting, yes. But it would be better to fix the problem if possible.
