### ISSUE TITLE
Explain why different test suites are needed

### ISSUE THREAD

**Issue by layday** [pypa/build#283]
It would be good to explain in the new test docs why the tests are split up between path, sdist and wheel, which might be non-obvious.

**Comment by henryiii** [comment]
Why are they needed? Can't we just have a test that makes sure the SDist is complete, and the wheel is complete, and reduce this to "run from source" (maybe even a partial suite) and "default install", and leave it at that? We could also still run the current tests on one or two matrix elements, but the entire thing is massive, and absorbs all the PyPA runners while running. We could also run a reduced test suite.

If we are going to parametrize something, it seems virtualenv/venv would be more important than running from path/sdist/wheel.

**Comment by layday** [comment]
I don't think we need to run the entire test suite from both sdist and wheel - it should be enough to verify that the contents fo the wheel produced from the sdist are the same.  The tox option IIUC builds a wheel from source using pip.  Again, a better option would be to verify that the wheel built by pip is equivalent to build's wheel, if maintaining parity is something we are interested in.

**Comment by henryiii** [comment]
This is exactly what it does:

https://github.com/pypa/build/blob/59a3f3dc404a93aee17c0df5a60c4cff1f44ff16/tests/conftest.py#L20-L59

So I'd think we just need some tests similar to https://github.com/pybind/pybind11/blob/master/tests/extra_python_package/test_files.py and that would be much, much faster to test.

**Comment by gaborbernat** [comment]
> running from path/sdist/wheel.

Running from the path was something @FFY00 wanted to add to make sure OS bootstrap that doesn't build wheels can work. For sdist/wheel I think was just a case of back then the test suite was small enough that wasn't that expensive. Nowadays, we can likely exchange it with a test that makes sure that sdist -> wheel == wheel, plus wheel tests.
