### ISSUE TITLE
API: Add a method to customise handling of build output

### ISSUE THREAD

**Issue by pfmoore** [pypa/build#289]
When calling the API (`builder.build()`) the backend output is sent directly to the terminal. There's no clear way to capture that output, either to redirect it to a log, or to save it for manual processing. This makes it very difficult to use the API without the caller's output being extremely cluttered.

Related: #188

For now, in my code, I am using

```python
build.pep517.default_subprocess_runner = build.pep517.quiet_subprocess_runner
```

to suppress output. Yes, I *know* this is an immense hack. Would a PR to allow use of a pep517 custom runner object at https://github.com/pypa/build/blob/main/src/build/__init__.py#L201 be accepted?

**Comment by pfmoore** [comment]
I've created #290 as an initial implementation, in case this is an acceptable feature request.

**Comment by FFY00** [comment]
Also related: #142
