### ISSUE TITLE
Build includes an old file that had been removed from the souce code

### ISSUE THREAD

**Issue by aendie** [pypa/build#291]
**My environment:**
Operating System:    Windows 10 Pro, Version 20H2, OS Build 19042.964
Python version:    3.9.4
Build installed via:    python -m pip install --upgrade build
Build version:   0.3.1.post1
Published PyPI containing the build error:   https://pypi.org/project/pyalmanac/1.2/

**Problem description:**
I recently noticed an incorrect build - the build included a file that I had deleted from the sources.

In my app/pyalmanac/lib folder I had 8 files, however one was a older copy that was not needed:

- alma_ephem.py
- alma_ephem - Copy.py

The last file should not be part of the built distribution. So I deleted it (also deleting the two files in app/dist) and re-ran "python -m build". I did not notice until later that "alma_ephem - Copy.py" was still part of the distribution. In fact I found it cached in app/build/lib/pyalmanac/lib folder. ONLY AFTER DELETING THE app/build FOLDER entirely did the build run correctly.

I hope you have enough information to detect the issue, if not, I'll gladly be of further assistance. My suspicion is that only the first 10 characters (alma_ephem) are compared, which also matches "alma_ephem - Copy" so it thinks it should remain in the distribution set. Just guessing! Thanks for your assistance.

**Comment by layday** [comment]
Thanks for reporting.  This is not an issue with build, which is just a frontend for other build tools - in this case, setuptools. The setuptools wheel builder merges the contents of the package folder it keeps in the "build" folder with every consecutive run (see https://github.com/pypa/wheel/issues/147).  To ensure that this does not happen in the future, delete your "build" folder before rebuilding.

**Comment by FFY00** [comment]
Exactly, `pypa/build` only invokes the backend, which is the one responsible for building the the actual distribution archives.

**Comment by layday** [comment]
build doesn't even know the "build" folder exists.
