### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by FFY00** [pypa/build#299]
I am thinking about making a release, does anyone want something merged/resolved before? @gaborbernat @layday @henryiii

**Comment by gaborbernat** [comment]
I'm good thanks ☺️

**Comment by henryiii** [comment]
You even got my "future wishlist" (#296) in (wow), so I'm good. :)

**Comment by layday** [comment]
All good from my end.

**Comment by FFY00** [comment]
Cool, I'll just wait a few days and then tag 0.4.0 :+1:

**Comment by FFY00** [comment]
0.4.0 released :tada:
