### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by FFY00** [pypa/build#313]
A couple changes have gone in, and I have some work blocked by them, so I would like to make a release. Does anyone have something they would like to get in too?

cc @pypa/build-team

**Comment by gaborbernat** [comment]
Go ahead 😊

**Comment by layday** [comment]
Yeah, go for it.

**Comment by henryiii** [comment]
Sounds good to me. :)

**Comment by FFY00** [comment]
I will tag tomorrow then.

**Comment by FFY00** [comment]
0.5.0 released.
