### ISSUE TITLE
0.4.0: --outdir fails when parent directory does not exist

### ISSUE THREAD

**Issue by kloczek** [pypa/build#316]
```console
+ cd rich-10.4.0
+ /usr/bin/python3 -m build --no-isolation --outdir build/lib
Traceback (most recent call last):
  File "/usr/lib64/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib64/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.8/site-packages/build/__main__.py", line 236, in <module>
    main(sys.argv[1:], 'python -m build')
  File "/usr/lib/python3.8/site-packages/build/__main__.py", line 228, in main
    build_package(args.srcdir, outdir, distributions, config_settings, not args.no_isolation, args.skip_dependency_check)
  File "/usr/lib/python3.8/site-packages/build/__main__.py", line 107, in build_package
    _build_in_current_env(builder, outdir, distributions, config_settings, skip_dependency_check)
  File "/usr/lib/python3.8/site-packages/build/__main__.py", line 84, in _build_in_current_env
    builder.build(dist, outdir, config_settings)
  File "/usr/lib/python3.8/site-packages/build/__init__.py", line 330, in build
    return self._call_backend(build, output_directory, config_settings, **kwargs)
  File "/usr/lib/python3.8/site-packages/build/__init__.py", line 340, in _call_backend
    os.mkdir(outdir)
FileNotFoundError: [Errno 2] No such file or directory: '/home/tkloczko/rpmbuild/BUILD/rich-10.4.0/build/lib'
```

**Comment by FFY00** [comment]
Dang, this just missed the 0.5.0 release.

The issue is that the code was not prepared for inexistent outdirs with multiple levels. It works if you do `mkdir build`, so you can use that (or just `mkdir build/lib` :stuck_out_tongue:) as a workaround in the meantime.

**Comment by FFY00** [comment]
Btw, if you are using this for distro packaging, you might want to add the `-w`/`--wheel` flags as from 0.5.0 and onwards invoking the CLI without `--sdist` or `--wheel` will build a sdist tarball, extract it, and build a wheel from it. This behavior is what most normal users probably want, but not distro packagers :blush:

**Comment by kloczek** [comment]
Thank you very much. Will test that ASP 😊
I found that issue by accident trying to build `rich` module which has sphinx documentation and I've been thinking about prepare `build/lib/` content which is needed to be able use `setuptools` build_sphinx command.
However as `build` produces only .whl archive looks like it cannot be used as `setuptools` build command replacement and that does not work of course.
Sphinx to generate documentation needs unpacked form of module ..

I still have no my set of rpm macros which will be used to build all packages which have `project.toml` file.
I don't wat to use fedora template to that kind of operations because tooling behind that tooling has **gigantic**  dependencies and IMO that is dead end (despite fact that fedora macros do not case about building and installing documentation is some unified way).
From that point of view I'm opened on **any suggestions** about how to organise template build of module documentation when `build` module is used.
