### ISSUE TITLE
build 0.5.0 wheel missing specified package data

### ISSUE THREAD

**Issue by matthewkotila** [pypa/build#323]
Short description:

I was building a python package wheel with build 0.5.0 and setuptools (57.0.0?) and noticed that my package data was missing. I downgraded build to 0.4.0 and saw that package data was back to being included again. It looks like build 0.5.0 causes wheel to miss specified package data.

Steps to reproduce:

1. be running some linux OS with Python 3.8.5+ and pip 20.0.2+ (i used the docker for ubuntu 20.04)
2. install pypa build 0.5.0:
```bash
python3 -m pip install build==0.5.0
```
3. make package directories:
```bash
mkdir -p /tmp/my_package/my_package /tmp/my_package/my_package/my_package_data
```
4. make `/tmp/my_package/my_package/__init__.py`:
```py
```
```bash
echo "" > /tmp/my_package/my_package/__init__.py
```
5. make package data (`/tmp/my_package/my_package/my_package_data/my_data.html`):
```html
hello
```
```bash
echo "hello" > /tmp/my_package/my_package/my_package_data/my_data.html
```
6. make `/tmp/my_package/pyproject.toml`:
```toml
[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
```
```bash
echo -e "[build-system]\nrequires = [\"setuptools\", \"wheel\"]\nbuild-backend = \"setuptools.build_meta\"" > /tmp/my_package/pyproject.toml
```
7. make setuptools config (`/tmp/my_package/setup.cfg`):
```cfg
[metadata]
name = my_package

[options]
packages = find:
include_package_data = True

[options.package_data]
my_package =
    my_package_data/*
```
```bash
echo -e "[metadata]\nname = my_package\n\n[options]\npackages = find:\ninclude_package_data = True\n\n[options.package_data]\nmy_package =\n    my_package_data/*" > /tmp/my_package/setup.cfg
```
8. build package:
```bash
python3 -m build /tmp/my_package
```
9. observe that there is _no_ package data (`my_data.html`) in the wheel:
```bash
unzip -l /tmp/my_package/dist/*.whl | grep my_data.html
<no output>
```
10. install pypa build 0.4.0:
```bash
python3 -m pip install --force-reinstall build==0.4.0
```
11. re-build package:
```bash
python3 -m build /tmp/my_package
```
12. observe that there _is_ package data (`my_data.html`) in the wheel:
```bash
unzip -l /tmp/my_package/dist/*.whl | grep my_data.html
<some output showing that my_data.html is in wheel>
```

**Comment by layday** [comment]
setuptools is misconfigured.  Please see https://github.com/pypa/build/issues/319#issuecomment-865206218.
