### ISSUE TITLE
Build version 0.5+ breaks package with Fortran/Numpy extension

### ISSUE THREAD

**Issue by gmloose** [pypa/build#326]
When I try to build a package with Fortran/Numpy extension, the build breaks with the following error:
```
f2py options: []
  adding 'build/src.linux-x86_64-3.6/RMextract/pyiri/fortranobject.c' to sources.
  adding 'build/src.linux-x86_64-3.6/RMextract/pyiri' to include_dirs.
error: f2py target_c file 'build/src.linux-x86_64-3.6/RMextract/pyiri/fortranobject.c' not found
```
I think the reason for this failure is that build 0.5+ uses the previously generated source distribution to build the wheel.  However, the source distribution is missing the `fortranobject.c` source. I'm not sure if this is a bug in `build`, or in `numpy`, which comes with a modified `Extension` class. Note that the source is searched in the build directory. I know I can work around this by using `build -w`, but the point is that the source distribution is missing a file.

BTW: The same error occurs (also with `build` version 0.4) when I try to run `pip install <tar-file>`, where `<tar-file>` is the source distribution that was created by `build`.

**Comment by gaborbernat** [comment]
> However, the source distribution is missing the `fortranobject.c` source.

This is the underlying issue we should be looking to fix. Where's `fortranobject.c` in the project, what's your packaging logic, are you using setuptools?

**Comment by henryiii** [comment]
It seems to be something that gets generated automatically, but I think it has to be listed explicitly. Specifically, numpy [generates it](https://github.com/numpy/numpy/blob/623bc1fae1d47df24e7f1e29321d0c0ba2771ce0/numpy/distutils/command/build_src.py#L573-L576) in the build directory, so if that is not in your include directories, it will fail. (The lines following that seem to be doing just that, but something is not working, obviously).

My guess is NumPy might provide new versions of some of the commands (`sdist`, `build_ext`, `build_py`, `install`, etc) that you might need to use. Specifically, something needs to call `build_src`. From a [quick look around](https://github.com/numpy/numpy/blob/623bc1fae1d47df24e7f1e29321d0c0ba2771ce0/numpy/distutils/command/build_py.py#L7), I think it's `build_py`. Something like this:

```python
setup(..., commands={"build_py": numpy.distutils.command.build_py.build_py})
```

"Extension" is little more than a data class - it is not given any hooks by setuptools/distutils to do anything. So it's quite possible you have to add one or more command overrides.

**Comment by gmloose** [comment]
As far as I understand it, `numpy` copies the files `fortranobject.h` and `fortranobject.c` from its own installation directory (`numpy/f2py/src` in `site-packages`) to the `build` directory. Apparently it does _not_ do this when building the source distribution, but only when building the binary distribution, which is why the subsequent build of the wheel fails.

If I build in two stages, using `-s` and `-w`, then the build of the wheel succeeds, but the source distribution is still broken.

I tried adding the `commands` option to `setup()`, but that gave a warning:
```
/usr/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'commands'
```
By replacing `commands` with `cmdclass` I got rid of the warning, but the build still fails with the same error.

**Comment by henryiii** [comment]
Sorry, yes, it's `cmdclass`, I was doing it from memory.

**Comment by henryiii** [comment]
I think it's https://github.com/lofar-astron/RMextract

**Comment by henryiii** [comment]
I was going to suggest https://github.com/numpy/numpy/blob/c59662e93a0040524689263e9cd86e54a383fc5c/numpy/f2py/__init__.py#L125 But it says "version added: 1.22" :)

**Comment by gmloose** [comment]
That's the correct repository, but I'm currently preparing it for publication on PyPI. For that, I do not only need to be able to build binary wheels, but also a working source distribution. You can checkout the `fix-setup` branch if you want.

**Comment by gmloose** [comment]
I tried to mimic the new feature in `numpy` 1.22, by adding the following lines to my `setup.py`:
```
f2py_srcdir = os.path.join(os.path.dirname(numpy.__file__), 'f2py', 'src')
include_dirs = [numpy.get_include(), f2py_srcdir]
:
:
setup(...
    ext_modules=Extension(..., include_dirs=include_dirs)
)
```
But that doesn't work either. When the binary build phase starts it still searches for `fortranobject.c` in the wrong build directory:
```
  f2py options: []
    adding 'build/src.linux-x86_64-3.6/RMextract/pyiri/fortranobject.c' to sources.
    adding 'build/src.linux-x86_64-3.6/RMextract/pyiri' to include_dirs.
  error: f2py target_c file 'build/src.linux-x86_64-3.6/RMextract/pyiri/fortranobject.c' not found
```

**Comment by gmloose** [comment]
OK, I finally tracked down the issue, which I think is a bug in how `Extension` in Numpy's `distutils` handles `pyf` source files. Here's the bug report: https://github.com/numpy/numpy/issues/19441.
This issue can be closed, since it's not a bug in `build`. Rather, I would say that its improved build isolation led to the discovery of the bug in Numpy's `distutils`.
