### ISSUE TITLE
[BUG] `version: file: <file>` error "does not comply with PEP 440" when it actually does

### ISSUE THREAD

**Issue by markoshorro** [pypa/build#330]
For `build` versions `0.5.0` and `0.5.1` I am getting the following error (which I do not get in `build==0.4.0`):

```
distutils.errors.DistutilsOptionError: Version loaded from file: src/__version__ does not comply with PEP 440:
```

My `setup.cfg` file contains, of course:

```
version: file: src/__version__
```

And the content of `src/__version__` is:

```
0.0.1a0
```

I have also tried this string embedded in the `setup.cfg` and it works. Besides, this is PEP 440 compliant, and I have tested this behavior in Python 3.7, 3.8 and 3.9, so I guess the bug must be in this module.

**Comment by layday** [comment]
The most likely explanation is that the version file is not included in the sdist and setuptools fails to report it as not existing.

**Comment by markoshorro** [comment]
@layday you are completely right. Adding a `MANIFEST.in` including the file solves the problem. Thanks for addressing my issue.
