### ISSUE TITLE
Inspect distribution from setup.py

### ISSUE THREAD

**Issue by bjlittle** [pypa/build#331]
Thanks for `pypa/build`, it's a real gem of a package.

I have more of a question than an issue, and I'm hoping the `pypa/build` community might be able to advise me.

Essentially, I want to be able to know at runtime within my package `setup.py` whether it is being executed as part of a `build_sdist` or `build_wheel`. Is this possible in a robust way?

I was hoping that `--config-setting` might be a means to pass state through somehow to the target package `setup.py` being built, but as I learnt this is solely for backend use, https://github.com/pypa/pep517/blob/master/pep517/wrappers.py#L290.

Any advice would be greatly appreciated. If it helps, the context and use case of this query is https://github.com/SciTools/cf-units/pull/191.

Many thanks 👍

**Comment by gaborbernat** [comment]
This is less of a question for this package, more a question for setuptools. You'll need to read up on setuptools and CMD objects. The wheel target has its own command. You can check what's the target. What do you want to achieve exactly?

**Comment by layday** [comment]
You should be able to inspect `sys.argv` but what are you actually trying to do? I can't tell from the PTR.

**Comment by bjlittle** [comment]
Thanks @gaborbernat and @layday much appreciated :+1: 

I figured what I needed was either from `build`, `pep517` or `setuptools`, but didn't quite know which part of the tooling chain to focus on... so I started at the top i.e., `pypa/build`

Essentially, my use case is to bundle additional `xml` configuration files from a third-party package, but **only** when building a wheel. This wheel already automatically bundles the necessary third-party shared library our project links against, but we also need additional third-party `xml` files to make the wheel complete as a package. This doesn't apply when building an sdist.

Hence, why at build time the need for our package to know how it's being built so as to include additional third-party files as part of the `package_data`.

A bit of an edge use case, I must confess, but does this help clarify?

I've worked around it using environment variables, but that feels like a bit of a hack and not very pythonic. I just wanted to tap into some expertise and advice from the community on the best pattern to adopt.

It seems that really I need to investigate what `setuptools` might offer. My hunch was that `pypa/build` and `pep517` are at too high a level, and you've pretty much confirmed this. Thanks :smile: 

Feel free to close this issue

**Comment by gaborbernat** [comment]
Per packaging best practices you should be able to generate the same wheel both from a  source distribution and a source tree. So I'm not entirely sure why you don't want to include these xmls in the sdist? How will the wheel generated from the sdist contain the xmls?

**Comment by bjlittle** [comment]
As you both suggested the `sys.argv` tells me everything I need to know, thanks.

@gaborbernat Good questions, and thanks for the best practise reminder 👍

There's a bit of context to this, and it's down to the way that the `udunits2` third-party package from `unidata` that we require, works.

Sadly we can't bundle the third-party XML files alone within the source tree or sdist as these might be incompatible with the version of `udunits2` that our package ends up linking against within an installation at runtime. The only time when it is safe to do this is when creating the wheel.

That said, I'll test to ensure that we adhere to the best practise workflow in order to avoid any downstream issues.

I really appreciate both your help @gaborbernat and @layday 🍻

I'll also close this issue now, with thanks 👍
