### ISSUE TITLE
build raises FileNotFoundError when trying to read requirements.txt

### ISSUE THREAD

**Issue by matteofrigo** [pypa/build#332]
In my `setup.py` I have a few lines that read the dependencies from a `requirements.txt` file:

```python
requirements = []
with open('requirements.txt', 'r') as f:
    for line in f:
        if line[0] == '#':
            continue
        requirements.append(line.rstrip('\n'))
```

This used to work well when running `python3 -m build`, but now it raises a FileNotFoundError for `requirements.txt`. Note that a few lines before I have another similar piece of code that does a similar thing for the version number (in that case in `<package>/__init__.py`), but in that case it works. I checked the permission on the files and they are identical.

This problem appeared after I upgraded build to 0.5.1. I had to downgrade to 0.4.0 (I haven't tried anything in between) to make it work.

Do you have any clue on what this is?

**Comment by gaborbernat** [comment]
You're not packaging your `requirements.txt` to your sdist, so the wheel build fails. Before we built sdist/wheel separately. Now we build wheel from sdist, exactly to catch such packaging bugs. You likely want to add `requiremenst.txt` to your `MANIFEST.in` file.

**Comment by matteofrigo** [comment]
Thanks a lot!
