### ISSUE TITLE
Full path in .tar.gz

### ISSUE THREAD

**Issue by gentlegiantJGC** [pypa/build#357]
Hello
I am not sure if this is a bug on your end or something I have done wrong.
The generated tar.gz file installs perfectly fine but when opened in the file explorer there is a much longer path than is needed.
The following is the path within the tar.gz file. I have omitted the path to the file itself.
`\D:\a\Amulet-Map-Editor\Amulet-Map-Editor\dist\tmprmzjym2u\amulet-map-editor-0.8.13.tar\amulet-map-editor-0.8.13\`
It looks identical to the path on the build system (we are using github actions)

The file that I am opening can be found here
https://pypi.org/project/amulet-map-editor/0.8.13/#files

The workflow that generated the file is here
https://github.com/Amulet-Team/Amulet-Map-Editor/blob/master/.github/workflows/python-build.yml

Relevant part of the workflow log
https://pastebin.com/ybNp2nM9

**Comment by layday** [comment]
Thanks for the report. This is a Python bug, see https://github.com/pypa/build/issues/255#issuecomment-794560752.

**Comment by gentlegiantJGC** [comment]
Okay thanks
