### ISSUE TITLE
Allways use virtualenv if available

### ISSUE THREAD

**Issue by FFY00** [pypa/build#358]
Currently, we check if build was installed with the virtualenv extra (only works on wheels, not eggs). I wonder if it would make sense to always enabling it if available.

https://github.com/pypa/build/blob/db905dbee2225e415fd252bae7ede7ef3b70fe2d/src/build/env.py#L64-L72

We could change this check to evaluate our requirements with the `virtualenv` extra set.

What do you think?

**Comment by layday** [comment]
We actually don't check that build was installed with the extra, we only check the installed virtualenv version satisfies the version constraint specified in the extra.

**Comment by FFY00** [comment]
My mistake then.
