### ISSUE TITLE
Refactor package fixtures

### ISSUE THREAD

**Issue by FFY00** [pypa/build#366]
Currently, we have a hand-written fixture for each helper test package. We could generate the fixtures automatically based on the packages available.

I have done this in other projects. Example:

https://github.com/FFY00/trampolim/blob/f3e8db8dea5607f708208b57de0d8bc49348a9d1/tests/conftest.py#L66-L96

When doing this, we could also drop the `test-` prefix from the packages, as it only makes things more confusing IMO.

**Comment by deepto98** [comment]
@FFY00 I'd like to work on this issue, can you assign this to me?

**Comment by FFY00** [comment]
You can just open a PR.
