### ISSUE TITLE
wheels created from `requests-cache` or `url-normalize` source distributions only contains metadata

### ISSUE THREAD

**Issue by benoit-pierre** [pypa/build#384]
```bash
▸ wget -q https://files.pythonhosted.org/packages/ec/ea/780a38c99fef750897158c0afb83b979def3b379aaac28b31538d24c4e8f/url-normalize-1.4.3.tar.gz
▸ tar xf url-normalize-1.4.3.tar.gz
▸ cd url-normalize-1.4.3
▸ python -m build --wheel
* Creating virtualenv isolated environment...
* Installing packages in isolated environment... (poetry>=0.12)
* Getting dependencies for wheel...
* Building wheel...
Successfully built url_normalize-1.4.3-py2.py3-none-any.whl
▸ unzip -l dist/url_normalize-1.4.3-py2.py3-none-any.whl
Archive:  dist/url_normalize-1.4.3-py2.py3-none-any.whl
  Length      Date    Time    Name
---------  ---------- -----   ----
     1070  1980-01-01 00:00   url_normalize-1.4.3.dist-info/LICENSE
       87  2016-01-01 00:00   url_normalize-1.4.3.dist-info/WHEEL
     3193  2016-01-01 00:00   url_normalize-1.4.3.dist-info/METADATA
      318  2016-01-01 00:00   url_normalize-1.4.3.dist-info/RECORD
---------                     -------
     4668                     4 files
```

No such issue when using `pip`:
```bash
▸ python -m pip wheel --no-deps url-normalize-1.4.3.tar.gz
Processing ./url-normalize-1.4.3.tar.gz
  File was already downloaded […]/url-normalize-1.4.3.tar.gz
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Building wheels for collected packages: url-normalize
  Building wheel for url-normalize (PEP 517) ... done
  Created wheel for url-normalize: filename=url_normalize-1.4.3-py2.py3-none-any.whl size=6814 sha256=aa1858ca9e313314bb73dfcfa148ffb31e8d76fe05a725990731c7f316f632b0
  Stored in directory: […]/.cache/pip/wheels/8d/bb/29/b30564ee9ae6deb89c4aac8cf2e4f27662d9ee69d77ddab992
Successfully built url-normalize
▸ unzip -l url_normalize-1.4.3-py2.py3-none-any.whl
Archive:  url_normalize-1.4.3-py2.py3-none-any.whl
  Length      Date    Time    Name
---------  ---------- -----   ----
     1060  1980-01-01 00:00   url_normalize/__init__.py
     2306  1980-01-01 00:00   url_normalize/tools.py
     6462  1980-01-01 00:00   url_normalize/url_normalize.py
     1070  1980-01-01 00:00   url_normalize-1.4.3.dist-info/LICENSE
       87  2016-01-01 00:00   url_normalize-1.4.3.dist-info/WHEEL
     3193  2016-01-01 00:00   url_normalize-1.4.3.dist-info/METADATA
      566  2016-01-01 00:00   url_normalize-1.4.3.dist-info/RECORD
---------                     -------
    14744                     7 files
```

`build` version: 0.7.0.

**Comment by henryiii** [comment]
Your SDist is empty. Build does Source -> SDist -> Wheel by default. You probably have an issue with your MANIFEST.in. It would be better to make proper SDists, but you can skip that by explicitly requesting `--wheel`.

**Comment by benoit-pierre** [comment]
Is there a way to get more verbose/debug information from `build`?

**Comment by layday** [comment]
Is your git repo inside another git repo?  Poetry might be using the outermost repo.

**Comment by benoit-pierre** [comment]
Yep, that's the issue. That's not great behavior on the part of poetry... Clearly I'm not the only one with this issue: see comments for https://aur.archlinux.org/packages/python-requests-cache and https://aur.archlinux.org/packages/python-url-normalize/.

**Comment by henryiii** [comment]
Or

```
GIT_CEILING_DIRECTORIES="$PWD/.." python -m build --wheel
```

;)

**Comment by layday** [comment]
When this came up before I suggested that Poetry should disable Git detection for sdists, might be worth bringing up on their tracker.

**Comment by henryiii** [comment]
Part of the problem is that build can't run directly on the SDist. Pip is running directly on the SDist, and therefore is probably expanding the SDist in a temporary directory, so that's why it's working with pip. If we supported similar behavior (#311), then this would have worked from build too.

**Comment by benoit-pierre** [comment]
`20.3.4` (the Arch packaged version).

**Comment by henryiii** [comment]
That's reassuring, consistency is good. :)

**Comment by layday** [comment]
> Part of the problem is that build can't run directly on the SDist. Pip is running directly on the SDist, and therefore is probably expanding the SDist in a temporary directory, so that's why it's working with pip. If we supported similar behavior (#311), then this would have worked from build too.

Even when build is invoked with --sdist --wheel (or sans args), we're unpacking the sdist in the folder where build is invoked.  pip is unpacking it in $TMPDIR.

**Comment by carlosal1015** [comment]
Thanks for the explanation @henryiii @benoit-pierre @layday @alex @jezdez . I am the maintainer of both packages on AUR, trying to understand how to fix the installation for everyone, thanks for the help.

**Comment by henryiii** [comment]
If we support running directly on `<file>.tar.gz`, that likely will be in the tmp folder, since there isn't a package dir in that case. (I'm also a fan of using tmp for everything, using a subfolder causes issues, including this one. Scikit-build uses a local folder and it's a constant headache, but kind of necessary for incremental builds. But doesn't mean I like it).
