### ISSUE TITLE
Coverage reports broken on Codecov since 10 Oct

### ISSUE THREAD

**Issue by layday** [pypa/build#397]
Since #371, Codecov is only reporting test coverage, see https://app.codecov.io/gh/pypa/build/compare/371.

**Comment by FFY00** [comment]
This might be related to https://github.com/nedbat/coveragepy/issues/1143, but I don't have time to investigate right now.

**Comment by layday** [comment]
Hmm yes, the PR appears to have coincided with the release of coverage 6 but I don't think it's related to that issue.  It looks like it's not recording coverage data for anything in the `.tox` folder.

**Comment by layday** [comment]
Possibly https://github.com/nedbat/coveragepy/issues/876.

**Comment by layday** [comment]
Okay, I guess that's the same issue being described.
