### ISSUE TITLE
Bump minimum packaging version to 21.1

### ISSUE THREAD

**Issue by layday** [pypa/build#404]
Because of https://github.com/pyparsing/pyparsing/issues/329, versions of packaging earlier than 21.1, which do not have an upper bound for pyparsing, are broken in combination with pyparsing >= 3, causing our minimum version tests to fail.

**Comment by henryiii** [comment]
pyparsing 3.* or 3.0.5? From what I understand this was caused by a change in 3.0.5 that breaks packaging.

**Comment by layday** [comment]
Yes, 3.0.5.

**Comment by layday** [comment]
New packaging version was released which did not fix the underlying issue but did exclude 3.0.5.
