### ISSUE TITLE
Support For External Data Files

### ISSUE THREAD

**Issue by kitterma** [pypa/build#414]
In setuptools using setup.py bdist_wheel you can build a wheel with data files (e.g. man pages for /usr/bin scripts).  There doesn't seem to be any way to do this with build.  Could this be supported?  Currently I can migrate zero of the projects I'm upstream for away from setuptools due to lack of support for data files.

**Comment by gaborbernat** [comment]
build does not handle packaging. build just facilitates the environment for the build backend to perform the packaging through the mechanism defined in PEP-518 and PEP-517. If the interface there does not allow this you'd need to suggest an extension to those PEPs. Ultimately, in this case, setuptools is still performing the package build so should be possible to do so though I believe.
