### ISSUE TITLE
0.7.0: `--config-setting` option does not work

### ISSUE THREAD

**Issue by kloczek** [pypa/build#417]
Looks like `--config-setting` option does not work.
All details are in https://github.com/sergey-dryabzhinsky/python-zstd/issues/71

**Comment by layday** [comment]
`--config-setting` does work, it's just completely unintuitive the way it works with setuptools. See previous discussions:

* https://github.com/pypa/build/issues/202#issuecomment-757373572
* https://github.com/pypa/build/issues/328#issuecomment-877028239

**Comment by kloczek** [comment]
So looks like documentation probably still should be updated :/

**Comment by kloczek** [comment]
OK `python3 -sBm build -w -C=--global-option=--external -C=--global-option=--legacy` works.

Closing
