### ISSUE TITLE
Migration to PyPA namespace

### ISSUE THREAD

**Issue by pganssle** [pypa/build#42]
Should we go ahead and move the project over to the PyPA namespace now, even though [this milestone](https://github.com/FFY00/python-build/milestone/1) has not been hit yet?

I think there's already broad agreement that that will be the eventual home for it, and it's probably best to minimize the number of links to the "old location" (particularly since the "old location" is in @FFY00's personal namespace, which will presumably eventually become his own personal fork, and can't just be a simple redirect).

I think that rather than waiting to complete everything for the milestone, we can do the migration today and call that milestone "Ready for PyPA recommendation" (i.e. the point at which we can migrate packaging.python.org to using `python-build`).

**Comment by gaborbernat** [comment]
I personally say we should wait until we're in a state to be publicized widely, and those tickets are blockers for that.

**Comment by FFY00** [comment]
> particularly since the "old location" is in @FFY00's personal namespace, which will presumably eventually become his own personal fork, and can't just be a simple redirect

Yes.

I really want #18 to land before moving to the PyPA. I wouldn't put Windows and macOS in CI as a blocker but since it should be fairly easy to add, it wouldn't stall much.

**Comment by gaborbernat** [comment]
Generally speaking, moving something to the PyPa is a statement that it's ready to use. IMHO we need to ensure it works for most use cases before we do this. Hence, why holding the isolated build, through testing as blockers for the move.

**Comment by pganssle** [comment]
> Generally speaking, moving something to the PyPa is a statement that it's ready to use.

I'm not sure if this is true, historically. We've got random stuff in there like [`easy_install`](https://github.com/pypa/easy_install) and [`distutils`](https://github.com/pypa/distutils) that were put there as experiments in moving them out of their respective packages. I'm also not sure if [this thing](https://github.com/pypa/browntruck) is anything.

I think much better milestones for "is this ready to use" will be:

1. When we start explicitly advertising it as ready to use.
2. When we replace references to `setup.py bdist_wheel sdist` with references to this package in packaging.python.org
3. When it hits 1.0
4. When we put the `Development Status :: 4 - Beta` and/or `Development Status :: 5 - Production/Stable` trove classifiers on it.

If y'all are fine with keeping it as is, and we think that we'll complete the milestone relatively soon _anyway_, I guess I'm in no rush. I just think that there are practical reasons to not be too conservative about the move and I don't think there will be any objections if we go ahead and do it now (particularly if we are clear about the plan and the current status).

**Comment by FFY00** [comment]
With the build isolation merged, the missing CI added and the test refactoring PR waiting for reviews, I think we should be ready to do this.

**Comment by pganssle** [comment]
Can we go ahead with this now? Particularly if a release is coming, it would be good to get the `project_urls` updated and such.

**Comment by FFY00** [comment]
Sure. I just pushed the release, we can fix the project url in a post-release.

As per [PEP 609](https://www.python.org/dev/peps/pep-0609), a [PyPA member should put forward the proposal in a PyPA communication channel and a PyPA committer should back it to trigger a vote](https://www.python.org/dev/peps/pep-0609/#pypa-committer-votes).

**Comment by pganssle** [comment]
For those following along at home: @gaborbernat and I nominated this project for inclusion in the PyPA [here](https://discuss.python.org/t/moving-python-build-to-pypa/4390/37?u=pganssle).

We're now waiting on the re-establishment of `pypa-committers` so we can take a vote.

**Comment by pradyunsg** [comment]
@FFY00 You might wanna pin this. :)

**Comment by FFY00** [comment]
Sure.

**Comment by FFY00** [comment]
@pganssle update on this? Are we still waiting on the mailing list?

**Comment by pganssle** [comment]
Mailing list just went up a few days ago, I will formally put this up for a vote on it tomorrow.

**Comment by di** [comment]
Are we planning to move this to `pypa/build` or `pypa/python-build`? Sorry if this has already been discussed elsewhere and I missed it. I think this would be an important detail to include in the proposal for a vote.

**Comment by pganssle** [comment]
> Sorry if this has already been discussed elsewhere and I missed it. I think this would be an important detail to include in the proposal for a vote.

That does not really feel so important as part of the vote, IMO.

I don't like either name, but I think `pypa/build` seems better?

**Comment by merwok** [comment]
I don’t find it great to read `pypa/packaging` or `pyca/cryptography` all the time to refer to these libs.  Cute names can be too obscure, but using the most generic terms also isn’t great IMHO.

**Comment by FFY00** [comment]
> I don’t find it great to read `pypa/packaging` or `pyca/cryptography` all the time to refer to these libs. Cute names can be too obscure, but using the most generic terms also isn’t great IMHO.

+1 on this.

Calling it `build` would be, arguably, nicer but it generates too much confusion. IMO we should go with `python-build`.

**Comment by gaborbernat** [comment]
I think pybuild to not clash with pyenvs existing python-build...?

**Comment by FFY00** [comment]
Hum... The problem with `pybuild` is that it is not that obvious the PyPI name is `build`.

**Comment by gaborbernat** [comment]
Then something else, but python-build is already taken sadly...

**Comment by FFY00** [comment]
Right. In lack of a better name `pypa/build` would be acceptable. I never used pyenv's python-build so I am not aware of how widespread it is, and consequently can't estimate the amount of confusion that it would generate :confused:

**Comment by merwok** [comment]
`pybuild` program already exists on Debian and derived OSes.

**Comment by gaborbernat** [comment]
This is now done.

**Comment by abitrolly** [comment]
This is still a pinned issue. Is there any reason to keep it pinned?
