### ISSUE TITLE
wheel --build-number not working

### ISSUE THREAD

**Issue by KleKwi** [pypa/build#421]
`python3 -m build --wheel --config-setting=--build-number='2'`

the filename not contain build number:
`mypkg-0.0.68-py3-none-any.whl`
should be like:
`mypkg-0.0.68-2-py3-none-any.whl`

**Comment by layday** [comment]
```
python3 -m build --wheel --config-setting=--build-number --config-setting=2
```

**Comment by layday** [comment]
https://github.com/pypa/setuptools/issues/2491

**Comment by KleKwi** [comment]
> ```
> python3 -m build --wheel -C--global-option=--build-number -C--global-option=2
> ```

This works, thanks.
Closing.
