### ISSUE TITLE
ModuleNotFoundError when cmdclass is used it setup.cfg

### ISSUE THREAD

**Issue by zluudg** [pypa/build#423]
Having the `cmdclass` option defined in `setup.cfg` causes `python -m build` to fail with a `ModuleNotFoundError`.

How to reproduce:

**setup.cfg**
```
[metadata]
name = cmdclass example

[options]
packages = find:
cmdclass =
    sdist = custom_build.CustomSdistCommand
```
**pyproject.toml**
```
[build-system]
requires = [
    "setuptools>=42",
    "wheel",
]
build-backend = "setuptools.build_meta"
```
**custom_build.py**
```
from setuptools.command.sdist import sdist

class CustomSdistCommand (sdist):
    def run(self):
        print('custom steps...')
        super(sdist, self).run()
```

Minimal example project here: [example.zip](https://github.com/pypa/build/files/7810679/example.zip)

My system:
```
me@computer $ python
Python 3.8.12 (default, Sep  9 2021, 11:38:31) 
[GCC 9.4.0] on linux
me@computer $ python -m build --version
build 0.7.0 (/path/to/python3.8/site-packages/build)
```

**Comment by gaborbernat** [comment]
This is likely a setuptools bug, them not adding the cwd to the sys.path. There's nothing the build tool can do, please open an issue on the setuptools bug tracker.

**Comment by layday** [comment]
You can change the build backend to `setuptools.build_meta:__legacy__` if you're looking for a quick fix.  But yes, this is unrelated to build.
