### ISSUE TITLE
tgz filename suffix not supported for sdist

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [pypa/build#428]
https://github.com/pypa/build/blob/main/src/build/__main__.py#L238 expects tar.gz

**Comment by layday** [comment]
This is according to the [spec](https://www.python.org/dev/peps/pep-0517/#source-distributions):

> The new restrictions for sdists built by PEP 517 backends are:
>
> *    They will be gzipped tar archives, with the `.tar.gz` extension. Zip archives, or other compression formats for tarballs, are not allowed at present.

**Comment by RonnyPfannschmidt** [comment]
:facepalm: i missed that detail
