### ISSUE TITLE
How to create a dist that is just a plain release not a pre-release w/ dev and date

### ISSUE THREAD

**Issue by mulkieran** [pypa/build#432]
This is just a request for help. I can't persuade build to create a dist with the correct version string which should be a plain release version string because the egg-info MANIFEST contains a pre-release version, with "dev" and a date. How do I fix that? I can fix that by passing parameter to "python setup.py sdist egg-info", but I can't figure out how to get build to acknowledge them.

**Comment by layday** [comment]
See [any of these issues](https://github.com/pypa/setuptools/issues/2491#issuecomment-1002471681) for how to pass configuration options to setuptools.

**Comment by mulkieran** [comment]
> See [any of these issues](https://github.com/pypa/setuptools/issues/2491#issuecomment-1002471681) for how to pass configuration options to setuptools.

I'm asking this question _after_ doing exactly that. Still stuck. I was hoping it was something that was so normally wanted that everybody but me already knows how off hand.

**Comment by layday** [comment]
Can you show us what you have tried?

**Comment by mulkieran** [comment]
Feel free to close. The source of the problem was an unsuspected setup.cfg file that had been ignored by the release practices I inherited from the original writer of the package I'm trying to release, but which is respected by this build tool.

**Comment by layday** [comment]
Alright, I'll close this one then.
