### ISSUE TITLE
[feature] Add sub command or flag to overwrite directory dist

### ISSUE THREAD

**Issue by zhongjiajie** [pypa/build#441]
For now, we can could python package by running the command `python -m build`. and both `tar.gz` and `whl` files would be created and location it to directory `dist`. but when I change versions of the package and re-run the command `python -m build`, the old package still exists.

could we add a flag `--overwirte, -o` to build, if user add this and we would clean the distribute dir first before we output our build result

**Comment by q0w** [comment]
`-o` (`--outdir`) flag already exists.

**Comment by zhongjiajie** [comment]
@q0w  It is not about specific the output directory, it is overwrite the exists the output dir

**Comment by q0w** [comment]
I mean `-o` flag is busy, it should be something else.

**Comment by zhongjiajie** [comment]
yeah, you're right

**Comment by Mr-Sunglasses** [comment]
We can use `-ow` for `--overwrite`, but I am a little bit confused if the default dir is `dist` then it can clean it but if the user has changed the outdir, then do we need to add an optional argument for it or we can manually run a checker to check the dir's.

cc. @zhongjiajie @layday

**Comment by zhongjiajie** [comment]
> We can use `-ow` for `--overwrite`, but I am a little bit confused if the default dir is `dist` then it can clean it but if the user has changed the outdir, then do we need to add an optional argument for it or we can manually run a checker to check the build dir and then clean it.
> 
> cc. @zhongjiajie @layday

I think we should delete the user custom dir if they config it

**Comment by Mr-Sunglasses** [comment]
@layday  to avoid any further confusion, it might be best to close this issue now.

**Comment by layday** [comment]
We couldn't agree that this is desirable, closing for now.
