### ISSUE TITLE
Move the build documentation to pypa.io

### ISSUE THREAD

**Issue by pradyunsg** [pypa/build#449]
This would involve:

- @ewdurbin adding a `build.pypa.io IN CNAME readthedocs.io.` record.
- *after* that is done, @FFY00 going to https://readthedocs.org/dashboard/pypa-build/domains/ and configuring it to redirect to build.pypa.io, and to use that as a canonical domain. For flit, this is what I had to do:

  <img width="582" alt="Screenshot 2022-03-22 at 09 01 09" src="https://user-images.githubusercontent.com/3275593/159444917-5e9aa737-de85-421b-92d6-7e7fee780f2c.png">

**Comment by ewdurbin** [comment]
Please add my user as a user (ewdurbin) as a maintainer on the project on readthedocs.org and I will happily get that up and running.

**Comment by ewdurbin** [comment]
After the last fiasco migrating all the readthedocs pages, I'm no longer comfortable adding CNAMEs without having access to update them later.

**Comment by henryiii** [comment]
I'd love to do this - `build.pypa.io` is a lot nicer to type and remember. @FFY00 if you could add me to readthedocs I can add Ee. We should also consider it for cibuildwheel @joerick - old links still work, right, they just redirect? It's nice being able to type `<project-name>.pypa.io` for pip, setuptools, pipx, flit, hatch, etc.
