### ISSUE TITLE
build strips away `rcX` from version string

### ISSUE THREAD

**Issue by Torxed** [pypa/build#453]
I'm not too familiar with build or the PEP world.
But something that's been working in the past working with pypi.org has been the use of release candidates or developer versions:
 * https://pypi.org/project/archinstall/2.3.0.dev0/

But to my surprise, the following [runner](https://github.com/archlinux/archinstall/blob/7f0ccbe87ed64dc25a2948579b332e1a7b6b0403/.github/workflows/python-publish.yml#L27) pushed a [v2.4.0](https://pypi.org/project/archinstall/2.4.0/) release when in fact it should have been [v2.4.0.RC2](https://github.com/archlinux/archinstall/blob/7f0ccbe87ed64dc25a2948579b332e1a7b6b0403/archinstall/__init__.py#L49):
```python
__version__ = "2.4.0.RC2"
```

Not sure if this is down to misconfiguration or the build line, or a bug in build.
But the rigidness of pypi.org makes this extremely frustrating as I now have a blocking version due to something that's been working before. And I cannot revert it.

**Comment by layday** [comment]
You have a version of `"2.4.0"` in your pyproject.toml: https://github.com/archlinux/archinstall/blob/v2.4.0.rc2/pyproject.toml#L7. Your build backend is flit.  I assume that you replaced flit's config with the standards-based `project` table between 2.3.3 and 2.4.0.RC2.  If you want flit to read the version from your `__init__.py` with your new set-up you have to [mark the version as dynamic](https://peps.python.org/pep-0621/#dynamic) and remove the `version` field from the `project` table.

**Comment by Torxed** [comment]
Fudge! I did! Apologies, obviously the fault was behind the wheel!
