### ISSUE TITLE
How to configure isolated build environment?

### ISSUE THREAD

**Issue by ZelphirKaltstahl** [pypa/build#456]
Hi! I've read <https://github.com/pypa/build/issues/292>, but I am not sure it is already the answer to my question, so I will ask here.

How can I specify packages, which are required in the isolated build environment?

I am building a package, which has the dependency of `jupyter-packaging`. I know I could create another virtual environment before invoking `build`, activate it, and use the `--no-isolation` to get dependencies installed, but would prefer, if there was any way to tell `build` which packages need to be present inside the isolated environment. Is there a way to do that?

**Comment by layday** [comment]
The canonical way to specify build dependencies is in the build system table of your `pyproject.toml`.

**Comment by henryiii** [comment]
FYI and unrelated, you don't need `"wheel"`, setuptools declares it through PEP 517 (and it is smart and only requires it for wheel building, not sdist making).
