### ISSUE TITLE
Add proxy flag

### ISSUE THREAD

**Issue by BradleyDS2** [pypa/build#464]
There does not appear to be an option to provide a proxy. On networks that require a proxy to download packages from pip, this results in build failing on "Installing packages in isolated environment... (setuptools)" as it is unable to obtain this package, so the build process fails.

**Comment by layday** [comment]
Thanks for the report. How do you normally pass the proxy URL to pip?

**Comment by BradleyDS2** [comment]
pip install setuptools --proxy https://user:password@proxyserver:port

For proxies that don't require credentials it would simply be

pip install setuptools --proxy http://proxyserver:port


Looking forward to this being added as a feature. My organisation requires a proxy to use pip, including on the gitlab-ci runners that are used to build python packages from commits.

**Comment by henryiii** [comment]
Can't you do `PIP_PROXY=https://user:password@proxyserver:port python -m build` ? You could even export it as an environment variable then it would always work in both pip and build automatically. We generally do not wrap pip commands because they are available via environment flags for pip already.

**Comment by BradleyDS2** [comment]
Alternative methods for passing proxy parameters for pip are covered in the documentation here https://pip.pypa.io/en/stable/user_guide/

**Comment by BradleyDS2** [comment]
I'll check if that works tomorrow, thank you.

**Comment by BradleyDS2** [comment]
For a bit more context, I'm using Gitlab-CI runner with the script (powershell) runner.

Tried the following with no success:
```
set PIP_PROXY=proxyaddress
set http_proxy=proxyaddress
set https_proxy=proxyaddress
```

PIP_PROXY doesn't appear to be covered in the pip documents.


The workaround I am currently using is to restrict the to a single Gitlab-CI runner that I have direct access to, then setting the proxy in C:\ProgramData\pip\pip.ini but this workaround is less than ideal.

Could you please add the - -proxy flag to be passed to pip, as setting the environment variables doesn't appear to work in all cases (or perhaps they're just more prone to suffering a PEBCAC).

**Comment by layday** [comment]
we'd probably want to take the same approach as in https://github.com/pypa/build/issues/410.

**Comment by gaborbernat** [comment]
@BradleyDS2 You probably want to follow https://pip.pypa.io/en/stable/user_guide/#using-a-proxy-server namely setting `http_proxy`, `https_proxy`. If that doesn't work you should open an issue to pip. I'm strongly -1 on adding any flags to be passed on to pip.

**Comment by henryiii** [comment]
I believe the powershell syntax is:
```powershell
$Env:PIP_PROXY = "proxyaddress"
```

All pip options have a `PIP_<option_name>` form, the docs don't separately mention each one.
