### ISSUE TITLE
Entry [tool.setuptools.packages.find] in pyproject.toml is ignored

### ISSUE THREAD

**Issue by mscheltienne** [pypa/build#481]
I'm using `pyproject.toml` for packaging, and for a `template` repository, it has an entry:

```
[tool.setuptools.packages.find]
include = ['template*']
exclude = ['template*tests']
```

My understanding was that this exclusion global pattern should not pick the test modules. Testing with Glob Tool, the pattern does work and matches the tests modules, but they still end up in the `.tar.gz` and `.whl` created by `python -m build`.

Is this a bug or intended behavior, and is there a way to exclude the test modules from the packaging?

**Comment by uranusjr** [comment]
Configurations under `tool` is specific to the tool you use, so for this one you should ask at https://github.com/pypa/setuptools.

**Comment by FFY00** [comment]
`build` simply invokes your chosen backend, in this case, setuptools. We don't handle any of these settings, setuptools is the one that is generating the aritfacts.

**Comment by FFY00** [comment]
For some reason I don't seem to be able to transfer this issue over to setuptools, which is weird because I should have triage access there. So I am just gonna close it. @mscheltienne please open an issue in setuptools instead, and let me know if you need me to clarify something.

**Comment by henryiii** [comment]
You don’t need wheel. Setuptools declares it via PEP 517. Otherwise yes. :)

**Comment by FFY00** [comment]
Yes, the backend is selected via those lines. `requires` specifies the needed requirements to build the package, and `build-backend` the build backend `build` will invoke.

**Comment by mscheltienne** [comment]
Ok thank you, I'll drop the `wheel` req. and move my other questions to the setuptools repo :)
