### ISSUE TITLE
Executable command not on my PATH after installation

### ISSUE THREAD

**Issue by DanielSank** [pypa/build#483]
I am attempting to follow [these instructions to release a Python package](https://packaging.python.org/en/latest/tutorials/packaging-projects/). In a virtualenv created via virtualenvwrapper, I did
```
pip install --upgrade build
```
Then
```
which build
```
returns nothing. Meanwhile, the library does appear to have been installed because I have
```
~/.virtualenvs/my_virtual_env/lib/python3.9/site-packages/build/
```
Why isn't the `build` command on my PATH? Is there some incompatibility between virtualenv and this library?

**Comment by layday** [comment]
The command for build is `pyproject-build`. You may also use `python -m build`.

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Comment by layday** [comment]
I will assume that worked for you :)
