### ISSUE TITLE
Growing out of zero-versions?

### ISSUE THREAD

**Issue by pradyunsg** [pypa/build#487]
The existing versioning policy seems to suggest that project is trying to follow Semantic Versioning.

Is there any particular reason that this project is still on a zero-version? It is the de-facto recommended tool for building wheels and sdists for publishing to PyPI, in a backend-agnostic manner -- it would be nice to not be on [0ver](https://0ver.org). :)

**Comment by layday** [comment]
I assume it is/was to allow the API to rapidly evolve but development has slowed down over the past several months. It'd still be nice to resolve #361 and a few remaining warts like https://github.com/pypa/build/issues/405 and https://github.com/pypa/build/issues/377 before v1.

**Comment by henryiii** [comment]
@FFY00 can probably answer best, but as I recall they had a remaining requirement before v1 was ready - I think it was #377, actually.

**Comment by pradyunsg** [comment]
Is there any reason those can't be resolved *after* a v1? It's always OK to bump to the next major version, when we want to make a backwards-incompatible changes.

The point of 0ver is exactly that "Oh, we want to fit in one last thing" aspects of handling changes makes it difficult to get to 1.0 -- and there's no reason to not go ahead and bump to v1 when this is already clearly functional and important. It's not perfect, but it can evolve even after hitting 1.0.0.
