### ISSUE TITLE
`python -m build` doesn’t check if Python version is compatible with `python_requires` / `Requires-Python`

### ISSUE THREAD

**Issue by manueljacob** [pypa/build#492]
If I have
```
[options]
python_requires = >= 3.13
```
in `setup.cfg` of a setuptools-built package, `python -m pip wheel .` aborts with “ERROR: Package 'pep517-helloworld' requires a different Python: 3.10.5 not in '>=3.13'”. However, `python -m build .` succeeds.

I think that `python -m build` should check if the Python version is compatible with `python_requires`, since the build process itself (e.g. in setup.py) could depend on a specific Python version.

**Comment by manueljacob** [comment]
Thank you for the quick answer, it sounds reasonable.

[The core metadata specification](https://packaging.python.org/en/latest/specifications/core-metadata/#requires-python) doesn’t say this is a build time requirement.

So if someone had a use case of requiring a specific Python version at build time, some other approach must be taken (raising an exception at build runtime is probably best).

**Comment by henryiii** [comment]
Yes, the is exactly what Numba discovered the hard way. You can't put an upper limit here, back solving doesn't work for an upper limit, so if you really know you won't work on 3.11, you can check for it and throw a helpful error in `setup.py` (other backends could provide something like this too).
