### ISSUE TITLE
How to first build and then install into a stage directory?

### ISSUE THREAD

**Issue by yurivict** [pypa/build#498]
By default ```build``` seems to build the source tarball and wheel.

I work in the context of the FreeBSD port. I need to (1) configure (2) build (3) install into a stage directory.

Using setup tools this is done like this:
(1) python setup.py config
(2) python setup.py build
(3) python setup.py install -record /usr/ports/science/py-xx/work-py39/.PLIST.pymodtmp  -c -O1 --prefix=/usr/local --single-version-externally-managed --root=/usr/ports/science/py-xx/work-py39/stage

What are the equivalent commands using ```build```?

We don't need source tarball and wheel. It should just build and then install into a stage directory.

**Comment by jmroot** [comment]
The python packaging powers that be have decreed, for better or worse, that installing directly is no longer supported. You have to build a wheel and then install that wheel, inefficient as that may seem to packagers like us.

So your equivalent commands need to involve a wheel installer as well as `build`, and would look something like:
1. `python setup.py config`
2. `python -m build --wheel --no-isolation --outdir /usr/ports/science/py-xx/work-py39`
3. `python -m installer /usr/ports/science/py-xx/work-py39/*.whl --destdir /usr/ports/science/py-xx/work-py39/stage`

Bear in mind that many modules won't even have a `setup.py` in this new PEP 517 world. I don't know that `installer` has any equivalent of the `-record` option at this stage either.

**Comment by yurivict** [comment]
Why are there 2 tools, build and pip, that both seem to do the same - install python projects?

**Comment by jmroot** [comment]
Pip is a package manager as well as a wheel builder and installer. Build is just a wheel builder. Pip's package management features are at best redundant and at worst actively get in the way when used by a package manager (or ports system).

**Comment by yurivict** [comment]
@jmroot 
Thank you for this information. It is very useful.

Yuri

**Comment by henryiii** [comment]
FYI, pip should hopefully eventually use `build` to do builds and `installer` to do the installing.

And for "direct installing" vs. wheels first, it's a design tradeoff. A package _author_ has to make sure both code paths work if there are two; this is much deeper into packaging that most package authors want to tread! It's not uncommon for someone to override `bdist_wheel` and/or `install` and forgot to override the other. Having one path is much simpler for authors, so there's a higher change of a package working if the procedure is always the same. You don't have to run a repair tool in-between wheel creation and installation, so it's really just moving files around and a tiny bit of file generation and caching.

**Comment by henryiii** [comment]
PS: same trade off as to source -> wheel vs. source -> sdist -> wheel. If build were to do the first one by default, the second one, which is how users will most often build wheels on platforms where they are not provided, will be more likely to be broken. For example, forgetting to put an important file into the SDist is only caught by the second path.

**Comment by yurivict** [comment]
I've suggested this [patch](https://reviews.freebsd.org/D36061) for the FreeBSD ports framework to fully support PEP-517 at the level of individual ports. It is based on build/installer packages.
