### ISSUE TITLE
author from pyproject.toml is wrong

### ISSUE THREAD

**Issue by JakobDev** [pypa/build#501]
Considering you have the follwing line, [as documented on packaging.python.org](https://packaging.python.org/en/latest/tutorials/packaging-projects/#configuring-metadata) in your pyproject.toml:
```toml
authors = [
  { name="Example Author", email="author@example.com" },
]
```
You build the project with `python -m build`. The METADATA file of you wheel will contain this:
```
Author-email: Example Author <author@example.com>
```
But it should contain this:
```
Author: Example Author
Author-email: <author@example.com>
```
This leads to broken project pages on PyPI.

**Comment by uranusjr** [comment]
According to PEP 621, `authors` in pyproject.toml maps to `Author-email`, so the result you get is correct. If this results in incorrect display on PyPI, you should file a bug to github.com/pypa/warehouse/ as a UI bug.

https://peps.python.org/pep-0621/#authors-maintainers

**Comment by webknjaz** [comment]
Looks like https://github.com/pypi/warehouse/pull/12018 resolves the issue on the PyPI side. This issue can be closed.
