### ISSUE TITLE
[question] How is the wheel file named?

### ISSUE THREAD

**Issue by yurivict** [pypa/build#505]
On some projects build creates a wheel file with the name *-py3-none-any.whl.
But one project the wheel file name is ```primme-3.2.1-cp39-cp39-freebsd_13_1_stable_amd64.whl```.

Is there a general pattern?

**Comment by henryiii** [comment]
It's named by the backend. The rules are mentioned in https://peps.python.org/pep-0427/ & apply to both tags in the metadata and the name. `*-py3-none-any.whl` indicates the build backend didn't detect any binary files, just Python ones. The specific tag (which, in the case of free_bsd, is not distributable via PyPI) is applied if binary extensions are detected.

**Comment by yurivict** [comment]
Thank you for this information.
