### ISSUE TITLE
Unclear how to install executables with build

### ISSUE THREAD

**Issue by yurivict** [pypa/build#507]
Some python projects install executable in addition to python files. For example the [ete](https://github.com/etetoolkit/ete) project installs the ```bin/ete3``` executable.

It isn't obvious how to achieve such effect with wheels built with ```build``` because .whl file doesn't seem to contain executables.

**Comment by henryiii** [comment]
It does. Here are some wheels with executables, taken from a list of things that pipx is good for:

build: make SDists and wheels
twine: upload SDists and wheels
cibuildwheel: make redistributable wheels
nox/tox: Python task runners
jupylite: WebAssembly Python site builder
black: Python code formatter
pypi-command-line: query PyPI

uproot-browser: ROOT file browser (HEP)
tiptop: fancy top-style monitor
rich-cli: pretty print files
cookiecutter: template packages
clang-format: format C/C++/CUDA code
pre-commit: general CQA tool
cmake: build system generator
meson: another build system generator
ninja: build system

How you make one depends on your build backend. For the modern ones, it’s:

https://github.com/scikit-hep/hist/blob/9d6543aa6737d74045cf4f9d3df95c5e70aacf40/pyproject.toml#L43-44

**Comment by yurivict** [comment]
I've ran build on twine.
The wheel file contains these files:
```
./twine-4.0.1.dist-info
./twine-4.0.1.dist-info/entry_points.txt
./twine-4.0.1.dist-info/METADATA
./twine-4.0.1.dist-info/top_level.txt
./twine-4.0.1.dist-info/LICENSE
./twine-4.0.1.dist-info/WHEEL
./twine-4.0.1.dist-info/RECORD
./twine
./twine/py.typed
./twine/settings.py
./twine/auth.py
./twine/wheel.py
./twine/package.py
./twine/utils.py
./twine/__init__.py
./twine/commands
./twine/commands/__init__.py
./twine/commands/register.py
./twine/commands/upload.py
./twine/commands/check.py
./twine/cli.py
./twine/exceptions.py
./twine/repository.py
./twine/__main__.py
./twine/wininst.py
```

These are same files that are placed into ```site-packages```.

But executable isn't in it.

**Comment by henryiii** [comment]
It gets generated when the wheel is installed from the metadata. It has the python path burned in as a shebang line on top and calls the entry point you request in the metadata.

**Comment by yurivict** [comment]
This is clear now.

Thank you for your explanation!

**Comment by eli-schwartz** [comment]
@yurivict

Classic `setup.py install` would not create an intermediate wheel, it would just take setup.py entries and generate *both* entry_points.txt as well as scripts for each entry during the install process.

Any wheel installer (such as https://github.com/pypa/installer/ or pip, but NOT `build`) goes the other way -- it retrieves entry_points.txt from the wheel, and uses that to generate scripts for each entry.
