### ISSUE TITLE
File not find when I use relative path in Extension include_dirs

### ISSUE THREAD

**Issue by HFrost0** [pypa/build#520]
Thanks for the great tool. I have a question for c/c++ extension. In setup.py, there is a c++ extension
```python
Extension(
    "mylib",
    ['src/mylib.cpp'],
    include_dirs=[
        '/absolute_path_to/third_party/boost/include',  # absolute path
        # 'third_party/boost/include',  # relative path, wouldn't work
    ],
),
```
when I use `'third_party/boost/include'` instead of absolute path, there is an error during `python -m build`
```
src/mylib.cpp:5:10: fatal error: 'boost/algorithm/string.hpp' file not found
```
For the reason, I notice `build` create a tmp dir, and copy source files to that dir, but it seems like `third_party` dir is not copied to that tmp dir. 

I find that when I use `pip install .`, there is no file not find problem. I'm not sure whether the problem is related to the `build`. Is there any way to use relative path for `python -m build`?

**Comment by FFY00** [comment]
This comes from your build backend, which I am assuming is setuptools.

I suspect it isn't including those files in the sdist. Can you check if `python -m build -w` works? This will build the wheel directly from source, bypassing the sdist building step. If it works then there is an issue regarding the sdist generation in your project.

**Comment by HFrost0** [comment]
`python -m build -w` works fine, thank you! My build backend is `setuptools`, so it's a issue related to `setuptools`? I wonder why not `build` simply build wheel from source instead from sdist in default situation.

**Comment by layday** [comment]
build assumes that you'll want to publish both an sdist and a wheel and that you'll want the wheel to be able to be built directly from the sdist.  It defaults to building wheels from sdists to catch configuration problems just like this one where you've got some files in your local tree/repo that are necessary for building the wheel but you are not bundling in the sdist.

**Comment by HFrost0** [comment]
Got it. thank you for your patience.

**Comment by HFrost0** [comment]
I use `MANIFEST.in` to include third_party dir
```
recursive-include third_party *
```
and it should works on the default situation.
