### ISSUE TITLE
How to emulate `upload -r fury`

### ISSUE THREAD

**Issue by jamesbraza** [pypa/build#522]
In my `~/.pypirc` I have:

```
[fury]
repository: https://pypi.fury.io/foo/
username: ${PUBLISH_TOKEN}
password: n/a
```

I used to publish to an internal Gemfury using `python setup.py sdist upload -r fury`.

Now I am adopting `build`.  The equivalent of `python setup.py sdist` is `python -m build --sdist`.

How can match `upload -r fury`?  Thank you in advance!

**Comment by gaborbernat** [comment]
You should be using twine for uploading to PyPI the output of build.

**Comment by jamesbraza** [comment]
Okay cool, thanks for confirming.  I will close this out.

With `setup.py` it was possible to do this with a one line command, so if anyone knows of a way to make `build` work with a one-liner, please feel free to share anytime.

**Comment by gaborbernat** [comment]
In the new world is not possible with one command.

**Comment by henryiii** [comment]
Well, `pipx run build && pipx run twine upload dist/*` is sort of one line. :) But yeah, two commands. I think twine has been strongly recommended over setup.py upload for quite some time, though, so it was two commands ever since that happened.
