### ISSUE TITLE
Consider dropping "PEP 517" from project's short description

### ISSUE THREAD

**Issue by pradyunsg** [pypa/build#529]
In the same vein as https://github.com/pypa/pyproject-hooks/issues/136, https://github.com/FFY00/python-pyproject-metadata/issues/10, and https://discuss.python.org/t/name-for-pyproject-toml-builds-and-peps/1659.

**Comment by henryiii** [comment]
Current: "A simple, correct PEP 517 build frontend"

Suggestion: "A simple, correct Python build frontend"

**Comment by FFY00** [comment]
The README and docs also need to be updated.

**Comment by henryiii** [comment]
What about changing the dependency to https://github.com/pypa/pyproject-hooks (https://pypi.org/project/pyproject-hooks/) - though not sure what the status is, PEP517 seems to be up too & updated more recently.

**Comment by pradyunsg** [comment]
Yea, pyproject-hooks still needs a release. It's what `pep517` is being renamed to: https://github.com/pypa/pyproject-hooks/issues/136

I think a separate issue to follow up on that would be a good idea. :)

**Comment by webknjaz** [comment]
I think this is already solved by https://github.com/pypa/build/pull/539. Somebody just needs to close this issue..
