### ISSUE TITLE
UTF-8 author name leads to Author-email field being encoded

### ISSUE THREAD

**Issue by foosel** [pypa/build#531]
I have a `pyproject.toml` containing my name and email in the `authors` field like this:

``` toml
authors = [
  { name = "Gina Häußge", email = "gina@octoprint.org" }
]
```

Running `python -m build` generates the following in `METADATA`:

```
Author-email: =?utf-8?b?R2luYSBIw6R1w59nZSA8Z2luYUBvY3RvcHJpbnQub3JnPg==?=
```

That in turn leads to an error when attempting to upload such a package to testpypi (I haven't yet tried production pypi but I would expect it to behave exactly the same):

```
❯ python -m twine upload --repository testpypi dist/*
[...]
ERROR    HTTPError: 400 Bad Request from https://test.pypi.org/legacy/
         '=?utf-8?b?R2luYSBIw6R1w59nZSA8Z2luYUBvY3RvcHJpbnQub3JnPg==?=' is an invalid value for Author-email. Error: Use a valid email address See https://packaging.python.org/specifications/core-metadata for more      
         information.
```

Should this maybe rather be `=?utf-8?b?R2luYSBIw6R1w59nZQ==?= <gina@octoprint.org>` in that `Author-email` field? Or maybe, given that [Core metadata specifications](https://packaging.python.org/en/latest/specifications/core-metadata/) says this:

> Whenever metadata is serialised to a byte stream (for example, to save to a file), strings must be serialised using the UTF-8 encoding.

just leaving UTF-8 strings as is and including them in the file unencoded would be the best way, but I don't know what side effects that might have.

In my `setup.py` based packages, `METADATA` looks like this and that works just fine on upload:

```
Author: =?utf-8?b?R2luYSBIw6R1w59nZQ==?=
Author-email: gina@octoprint.org
```

So, if push comes to shove, splitting the values up like this might be the easiest solution to this issue, as already mentioned in #501. Being forced to write my name ASCII only certainly feels wrong in 2022 ;)

**Comment by foosel** [comment]
Addendum: `twine check` says "everything is great!" even with that `Author-email` field. I feel betrayed 😂

```
❯ twine check dist/*
Checking dist/OctoPrint_Setuptools-1.0.0-py3-none-any.whl: PASSED
Checking dist/OctoPrint-Setuptools-1.0.0.tar.gz: PASSED
```

**Comment by henryiii** [comment]
> Addendum: twine check says "everything is great!"

`twine check` checks practically nothing. It's quite hard to find a bug it can catch. ;)

This is a function of your build backend - what build backend are you using?

**Comment by abravalheri** [comment]
Might be related to https://github.com/pypa/wheel/issues/488.

**Comment by FFY00** [comment]
`build` is simply a frontend for the build process, it just invokes the build backend, which I assume is `setuptools`. `setuptools` is the one creating the metadata file.

From my understanding, the `METADATA` file is not UTF-8, so each field needs to be manually encoded. Perhaps something broke there.

As @abravalheri pointed out, that `wheel` issue seems related.

**Comment by foosel** [comment]
Ah, thanks, yes, that `wheel` ticket looks *very* much like it.

For reference, my build system definition:

``` toml
[build-system]
requires = [
    "setuptools>=40.8.0",
    "wheel"
]
build-backend = "setuptools.build_meta"
```

And apologies, I'm still getting my bearings with the fancy new stuff after coming from a decade of `setup.py` :)

In that case, happy to close this and sub to the `wheel` issue instead, thanks and apologies for the noise!

**Comment by FFY00** [comment]
No worries, happy to help :blush:
