### ISSUE TITLE
Add verbosity controls

### ISSUE THREAD

**Issue by wimglenn** [pypa/build#546]
`python -m build` with setuptools backend puts about 1000 lines to my log in github actions and it's hard to find what you're looking for.  It would be nice to have some verbosity controls without having to use grep hacks. I've just checked and most of those lines were stuff like `adding 'mypkg/foo/bar.py'` (~220) or `copying something -> somewhere` (~630).

`python -m pip wheel --no-deps .` has about the right amount of verbosity, and can be pumped up with `-v` or `-vv` etc if wanted, it would be nice to get something in `build`.  I tried to look for a way to plumb verbosity through to the backend using `--config-setting` but couldn't figure it out.

**Comment by layday** [comment]
Thanks for the suggestion; this is already being tracked in https://github.com/pypa/build/issues/546.  In the meantime, you can try passing `-q` as a global option to setuptools: `python -m build -C--global-option=-q`.
