### ISSUE TITLE
Release 0.10.0 with flit build system

### ISSUE THREAD

**Issue by nanonyme** [pypa/build#549]
Please tag a release of this project. It is now the final step of milestone for bootstrapping fully functional pyproject build system and installer.

**Comment by henryiii** [comment]
We need to support Packaging 22 first. Looks like a few of our tests are failing due to normalization issues - I _think_ they need to be adapted for PEP 685.

**Comment by nanonyme** [comment]
Okay, cool. We just switched in our build system to use pypa/build last weekend but have dependency issue which prevents building pypa/wheel with pypa/build until this is fixed.

**Comment by layday** [comment]
https://github.com/pypa/build/pull/550

**Comment by nanonyme** [comment]
Are there still further PR's that are desired to be merged before release?

**Comment by nanonyme** [comment]
I guess no more release blockers as https://github.com/pypa/build/pull/539 is merged?

**Comment by rossburton** [comment]
I want to move our building to use pypa/build but I don't like shipping 0.9.0+patches.  Any progress on a release?

**Comment by henryiii** [comment]
Friendly ping @FFY00. I can do the release if we get it set up.

**Comment by FFY00** [comment]
Thank you for the ping, and sorry for the delay in getting this release out. I have pushed 0.10.0.

@henryiii I will open a new issue regarding setting up the release requirements for the other maintainers.

**Comment by nanonyme** [comment]
Thank you <3. We were now finally able to drop setuptools into a second-tier citizen in our dependency tree.

**Comment by rossburton** [comment]
Ditto.  https://lore.kernel.org/openembedded-core/20230112112336.2254765-3-ross.burton@arm.com/T/#u integrates build as the primary building tool for all of our python.
