### ISSUE TITLE
Support for building Windows EXE and MSI files (was: `bdist_wininst`, `bdist_msi`) 

### ISSUE THREAD

**Issue by bittner** [pypa/build#582]
For building Windows EXE and MSI installer binaries there used to be two setuptools commands, `bdist_wininst` and `bdist_msi`, that [were removed](https://github.com/pypa/setuptools/blob/main/CHANGES.rst#v6500) in Python 3.10.

What is the suggested way to build those artifacts today, with Python versions 3.10+?

Will `build` ever support building those installer binaries, like setuptools did?

**Comment by uranusjr** [comment]
The suggestion is to not build those. Use wheels.

**Comment by FFY00** [comment]
> What is the suggested way to build those artifacts today, with Python versions 3.10+?

Like @uranusjr suggested, either just use wheels, or have a look at something like https://pyinstaller.org/en/stable/ or https://github.com/takluyver/pynsist for standalone distributions.

> Will `build` ever support building those installer binaries, like setuptools did?

If that functionality is ever standardized, we would consider it, but I highly doubt it personally.

---

I know this isn't exactly the answer you were hoping for, but I hope it helps.

**Comment by bittner** [comment]
> I know this isn't exactly the answer you were hoping for, but I hope it helps.

@FFY00 Don't worry, I'm just trying to clarify the topic (for everyone). I'm not a "Windows person", so no offense taken.

Actually, I was surprised to find out how easy it was to build an installer for Windows using Python's (former) default tool chain.

> The suggestion is to not build those. Use wheels.

@uranusjr Who's decision or suggestion is this? Can you substantiate your claim? Maybe link to a related discussion?

We all must understand that Windows people expect to have "installers". Telling them to run `pip install` (with all the difficulties that the Python setup on Windows entails) is not going to cut it. It will make Python software less accessible on their platform.

**Comment by FFY00** [comment]
> @uranusjr Who's decision or suggestion is this? Can you substantiate your claim? Maybe link to a related discussion?

Wheels are the only supported format for Python package distribution in standardized tooling. Other formats were never supported in the interchangeable build backends specification, see [PEP 517](https://peps.python.org/pep-0517/), and were ultimately deprecated in PyPI in 2016, via [PEP 527](https://peps.python.org/pep-0527/), and its discussion is available at https://mail.python.org/pipermail/distutils-sig/2016-August/029542.html.

> We all must understand that Windows people expect to have "installers". Telling them to run `pip install` (with all the difficulties that the Python setup on Windows entails) is not going to cut it. It will make Python software less accessible on their platform.

You can still do this, you can ship an installer that has a way to select the Python interpreter, but I don't think that provides *that* much value.

I think you need to evaluate the UX for your users here. Are you shipping a library? If so, then expecting your users to be comfortable running `pip install` is reasonable. Are you shipping an app? Then you probably want to provide Windows users with an installer of some sort, or a single-executable app, you can use something like [PyInstaller](https://pyinstaller.org/en/stable/), [Pynsist](https://github.com/takluyver/pynsist), or [PyOxidizer](https://github.com/indygreg/PyOxidizer), to acheive this.
