### ISSUE TITLE
Building packages that use setuptools_scm for versioning

### ISSUE THREAD

**Issue by vthemelis** [pypa/build#600]
Hi,

I'm using setuptools_scm for versioning my package.

When running 'python -m build .', I get a tarball with a version that has the correctly inferred version (through SCM) but the wheel has some default version. 

I think that's because the wheel is built in a separate location, outside the git repository. 

Could you suggest a workaround so that my wheel gets built with the correct version?

**Comment by FFY00** [comment]
Can you share your sources?

**Comment by henryiii** [comment]
There are a lot of packages using setuptools_scm (and hatch-vcs, which is a wrapper for it) and build together, including most of my packages. So I expect something else is wrong, but can't say more without some source code.

**Comment by vthemelis** [comment]
It looks like the issue is on my side with the way that I'm using `setuptools_scm`.

My process was failing to deduce the correct version while building inside of `/private/var/folders/yn/hyzy_z110_b4nlttdd_vxlfw0000gn/T/build-via-sdist-o6ugh2_t/mypackage-0` (example directory) but vanilla `setuptools_scm` seems to work fine even on this  situation.
