### ISSUE TITLE
Generated wheels are incomplete compared to `pip wheel`

### ISSUE THREAD

**Issue by FriedrichFroebel** [pypa/build#603]
Using `python -m build .` (version 0.10.0) appears to generate incomplete wheels in some cases, omitting the actual library code. Take https://github.com/FriedrichFroebel/pelican-youtube-thumbnails as an example, where the complete `pelican` directory is missing from the wheel:

```bash
me@localhost ~/pelican-youtube-thumbnails/dist $ unzip pelican_youtube_thumbnails-0.3.2-py3-none-any.whl 
Archive:  pelican_youtube_thumbnails-0.3.2-py3-none-any.whl
  inflating: pelican_youtube_thumbnails-0.3.2.dist-info/COPYING  
  inflating: pelican_youtube_thumbnails-0.3.2.dist-info/METADATA  
  inflating: pelican_youtube_thumbnails-0.3.2.dist-info/WHEEL  
  inflating: pelican_youtube_thumbnails-0.3.2.dist-info/top_level.txt  
  inflating: pelican_youtube_thumbnails-0.3.2.dist-info/RECORD  
```

Running `pip wheel -w ist --no-deps .` (version 0.37.1) instead, the correct file content will be generated:

```bash
me@localhost ~/pelican-youtube-thumbnails/dist $ unzip pelican_youtube_thumbnails-0.3.2-py3-none-any.whl 
Archive:  pelican_youtube_thumbnails-0.3.2-py3-none-any.whl
  inflating: pelican/plugins/youtube_thumbnails/__init__.py  
  inflating: pelican/plugins/youtube_thumbnails/logo.png  
  inflating: pelican/plugins/youtube_thumbnails/youtube_thumbnails.py  
  inflating: pelican_youtube_thumbnails-0.3.2.dist-info/COPYING  
  inflating: pelican_youtube_thumbnails-0.3.2.dist-info/METADATA  
  inflating: pelican_youtube_thumbnails-0.3.2.dist-info/WHEEL  
  inflating: pelican_youtube_thumbnails-0.3.2.dist-info/top_level.txt  
  inflating: pelican_youtube_thumbnails-0.3.2.dist-info/RECORD  
```

**Comment by layday** [comment]
Probably an sdist file inclusion issue.  build builds wheels from sdist; `pip wheel` builds them directly from source.  Ensure that the "pelican" folder is included in the sdist.

**Comment by FriedrichFroebel** [comment]
Running `python setup.py sdist` will include these files as well:

```bash
me@localhost ~/pelican-youtube-thumbnails/dist $ tar -xvf pelican-youtube-thumbnails-0.3.2.tar.gz 
pelican-youtube-thumbnails-0.3.2/
pelican-youtube-thumbnails-0.3.2/COPYING
pelican-youtube-thumbnails-0.3.2/MANIFEST.in
pelican-youtube-thumbnails-0.3.2/PKG-INFO
pelican-youtube-thumbnails-0.3.2/README.md
pelican-youtube-thumbnails-0.3.2/pelican/
pelican-youtube-thumbnails-0.3.2/pelican/plugins/
pelican-youtube-thumbnails-0.3.2/pelican/plugins/youtube_thumbnails/
pelican-youtube-thumbnails-0.3.2/pelican/plugins/youtube_thumbnails/__init__.py
pelican-youtube-thumbnails-0.3.2/pelican/plugins/youtube_thumbnails/logo.png
pelican-youtube-thumbnails-0.3.2/pelican/plugins/youtube_thumbnails/youtube_thumbnails.py
pelican-youtube-thumbnails-0.3.2/pelican_youtube_thumbnails.egg-info/
pelican-youtube-thumbnails-0.3.2/pelican_youtube_thumbnails.egg-info/PKG-INFO
pelican-youtube-thumbnails-0.3.2/pelican_youtube_thumbnails.egg-info/SOURCES.txt
pelican-youtube-thumbnails-0.3.2/pelican_youtube_thumbnails.egg-info/dependency_links.txt
pelican-youtube-thumbnails-0.3.2/pelican_youtube_thumbnails.egg-info/requires.txt
pelican-youtube-thumbnails-0.3.2/pelican_youtube_thumbnails.egg-info/top_level.txt
pelican-youtube-thumbnails-0.3.2/setup.cfg
pelican-youtube-thumbnails-0.3.2/setup.py
pelican-youtube-thumbnails-0.3.2/tests/ 
```

**Comment by layday** [comment]
It's because `pelican/__init__.py` doesn't get bundled in the sdist so `find_packages` in your `setup.py` does not consider "pelican" and therefore its subfolders in your sdist to be packages.  See https://setuptools.pypa.io/en/latest/userguide/quickstart.html#package-discovery.

**Comment by henryiii** [comment]
FYI, I wrote a little tool, `pipx run check-sdist`, that can detect differences like this between SDist and git.

**Comment by FriedrichFroebel** [comment]
> It's because `pelican/__init__.py` doesn't get bundled in the sdist so `find_packages` in your `setup.py` does not consider "pelican" and therefore its subfolders in your sdist to be packages.

I actually debugged through this to fix some initial issues with the used patterns, as `find_packages` would never consider `pelican` at all when no `__init__.py` file has been present in the corresponding directory. Using `find_namespace_packages` instead fixes this, but breaks both `wheel` and `build`.

The directory/package structure `pelican/plugins/youtube_thumbnails` is the recommended approach for extending the `pelican` package with plugins, so I would have expected this to not cause such issues: https://docs.getpelican.com/en/latest/plugins.html#how-to-use-plugins Deploying my own `__init__.py` files would conflict with `pelican` itself, as this might replace files like https://github.com/getpelican/pelican/blob/master/pelican/__init__.py with empty ones.

What would be the correct approach here? While I could live with calling two commands, using the recommended `build` command before the PyPI upload seems much more appropriate.

**Comment by layday** [comment]
> Using `find_namespace_packages` instead fixes this, but breaks both `wheel` and `build`.

Breaks them how?

**Comment by FriedrichFroebel** [comment]
> Breaks them how?

Sorry, my mistake - apparently I missed to replace the `find_packages` as well, not only add the new import. With namespace package support enabled, `python -m build .` and `pip wheel .` will generate the correct wheels.

I assume that using the new namespace package finder of `setuptools` is indeed the solution in this case to not break the `build` package with this constellation?

**Comment by layday** [comment]
You should remove `__init__.py` from `pelican` and `pelican/plugins` and change `find_packages` to `find_namespace_packages`.

**Comment by FriedrichFroebel** [comment]
This is what I basically did with my last comment. Thanks for the hint. I am going to close the issue for this reason.
