### ISSUE TITLE
Error building source distributions when the filename does not match archive name

### ISSUE THREAD

**Issue by ofek** [pypa/build#607]
https://github.com/pypa/hatch/issues/833#issuecomment-1519115885

![bb](https://user-images.githubusercontent.com/9677399/233856704-0891dca5-a716-4d81-88e1-c77073ccd8e2.PNG)

```
❯ python -m build
* Creating virtualenv isolated environment...
* Installing packages in isolated environment... (hatchling)
* Getting build dependencies for sdist...
* Building sdist...
ERROR Source C:\Users\ofek\AppData\Local\Temp\build-via-sdist-eu6in06u\github3.py-4.0.0 is not a directory
```

I think the filename should not be taken into account.

**Comment by layday** [comment]
What do I have to do to reproduce this? I cloned [github3.py](https://github.com/sigmavirus24/github3.py)'s main branch and ran build on it and it seems to work fine.

**Comment by layday** [comment]
Right, I needed to disable `strict-naming`.

**Comment by layday** [comment]
I'm inclined to close this as won't fix. build follows [PEP 625](https://peps.python.org/pep-0625/), which says that:

> The name of an sdist should be `{distribution}-{version}.tar.gz`.
> * `distribution` is the name of the distribution as defined in [PEP 345](https://peps.python.org/pep-0345), and normalised as described in [the wheel spec](https://packaging.python.org/en/latest/specifications/binary-distribution-format/) e.g. `'pip'`, `'flit_core'`.

**Comment by ofek** [comment]
I think a frontend doing anything but invoking the backend is out of scope. It should be up to the backend what to name the file and wouldn't put any extra maintenance burden here as far as I can tell.

Do you know exactly why this error is happening? Is the source distribution being extracted and the inner directory is trying to be located to build the wheel based on the original filename?

**Comment by layday** [comment]
Pretty much; build calls `basename` on the filename of the sdist to trim the extension, then once it unpacks the sdist, it attempts to access `temp_dir/basename`.  The packed folder has an underscore where the sdist has a dot.  I suppose we could call grab the top-level folder's name from the contents of the sdist, but we didn't think that the filename and folder name would differ.

**Comment by ofek** [comment]
I think it would make sense to fix it here because building the source distribution separately from the wheel does indeed work properly

**Comment by ofek** [comment]
If you don't think so then I will fix in Hatchling today, just let me know!

**Comment by layday** [comment]
But what is build expected to do if `$(basename $filename .tar.gz) != $filename`?  Traverse the containing folder and pick the first unpacked folder it finds?  What if there's multiple top-level directories?  It just seems more sensible to assume that the above condition is always `==`.

**Comment by offbyone** [comment]
I don't know how significant this is, but `build` has different behaviour in sdist construction depending on how it's invoked:

```shellsession
$ python -mbuild
* Creating virtualenv isolated environment...
* Installing packages in isolated environment... (hatchling)
* Getting build dependencies for sdist...
* Building sdist...
ERROR Source /var/folders/tc/mhq0tfws3s1bs5788hx6nhkc0000gn/T/build-via-sdist-6wbzvh9r/github3.py-3.2.0 is not a directory

$ python -mbuild -s
* Creating virtualenv isolated environment...
* Installing packages in isolated environment... (hatchling)
* Getting build dependencies for sdist...
* Building sdist...
Successfully built github3.py-3.2.0.tar.gz
```

**Comment by ofek** [comment]
> Traverse the containing folder and pick the first unpacked folder it finds?

Yes I think

> What if there's multiple top-level directories?

That would never happen, or at least that wouldn't be a source distribution

**Comment by ofek** [comment]
Twine also handles archive component names in an agnostic way:

- https://github.com/pypa/twine/blob/9c2c0a1c535155931c3d879359330cb836950c6a/twine/package.py#L34
- https://bazaar.launchpad.net/~tseaver/pkginfo/trunk/view/221/pkginfo/sdist.py#L43

**Comment by layday** [comment]
Sdists are not particularly well defined - I'm not sure that having multiple folders is disallowed, or that it would be any less surprising than the a top-level folder having a different name from the archive itself.  I'd suggest applying the principle of least surprise here - keeping the outer and inner names the same if there's no good reason that they should differ.   [PEP 517](https://peps.python.org/pep-0517/#source-distributions) does also mention that: "[the sdist format] is mostly undefined, but basically comes down to: a file named `{NAME}-{VERSION}.{EXT}`, which unpacks into a buildable source tree called `{NAME}-{VERSION}/`."  I overlooked this earlier.

**Comment by ofek** [comment]
https://github.com/pypa/hatch/releases/tag/hatchling-v1.14.1
