### ISSUE TITLE
PyPI is stale

### ISSUE THREAD

**Issue by jaraco** [pypa/build#615]
I'm still experiencing the problems reported in #577. Would someone consider cutting a release?

**Comment by szobov** [comment]
Hi there,
I'm very sorry for the extra noise, but what is the release status?
There are some unreleased changes merged around 7 months, but the last release was on 11 January.
If you need any help with releasing it please let us know. :)
Thanks!

**Comment by henryiii** [comment]
https://pypi.org/project/build/1.0.0/

:tada:
