### ISSUE TITLE
[UX] Quote individual dependencies in the list logged to console

### ISSUE THREAD

**Issue by webknjaz** [pypa/build#617]
See
```console
* Installing packages in isolated environment... (Cython, expandvars, setuptools-scm-git-archive >= 1.1; python_version < '3.7', setuptools-scm[toml] >= 3.5, < 7.0; python_version < '3.7', setuptools-scm[toml] >= 7.0; python_version >= '3.7', setuptools>=45, toml)
```

There's a few dependencies that are conditional on environment and/or have complex version specifiers. In it, a comma is use in two contexts — as a package request separator and as a separator of parts of a version specifier. This is something an inexperienced individual could easily get confused about when reading the logs.

I think that these deps should be `repr()`ed or smth similar for clarity.

**Comment by layday** [comment]
PR improving the CLI output welcome :)

**Comment by webknjaz** [comment]
It seems like here's a PR now: https://github.com/pypa/build/pull/711

**Comment by layday** [comment]
Addressed in https://github.com/pypa/build/pull/749.
