### ISSUE TITLE
How to build source distribution [sdist] excluding  particular file 

### ISSUE THREAD

**Issue by Earammak** [pypa/build#643]
I need help in building source distribution to exclude a particular file for my project.
We are giving python wheels support to our project [ https://github.com/ibmdb/python-ibmdb].
So, the requirement is while building source distribution file should not be included and when it is building wheel it should be included in .whl file.

Source distribution and wheels are created from github actions.
Is there a way to exclude file to create a source distribution. 

Thanks,

**Comment by abravalheri** [comment]
Hi @Earammak, this is probably a question for the build backend that your project uses...

In general, a project should be able to build from the `sdist`, so unless you are generating the file dynamically during the build, you might not be able to include it later in the wheel if it is not originally included in the `sdist`.

If you are generating the file dynamically, whether it is included on the `sdist` or `wheel` will depend on how you are customising the build process.

I see that in https://github.com/ibmdb/python-ibmdb you are using `setuptools` as build backend, so I recommend opening a GitHub discussion in pypa/setuptools with a minimal reproducer of what you want to achieve.

**Comment by Earammak** [comment]
@abravalheri, Thank you for quick update. 
To build source distribution we will use a command is: " python -m --sdist --no-build-isolation "

From this build package, do we have any config that we can exclude while building source distribution ?

**Comment by abravalheri** [comment]
Have you tried [`MANIFEST.in`](https://packaging.python.org/en/latest/guides/using-manifest-in/)?

**Comment by Earammak** [comment]
Yes i tried. 
From source distribution the file will be excluded. 
But i need that file while installing the package from that source distribution. [ To download the file we have coded in setup.py]

**Comment by abravalheri** [comment]
That is the thing that I was referring in my first comment... If you are not generating this file dynamically, then you do need to include it in the `sdist`, otherwise it will not be available when creating the wheel.

**Comment by abravalheri** [comment]
I am not sure if I understood, sorry, it is very difficult to discuss in terms of generic process and generic files 😅.

If you need to download a file for each platform when creating the wheel, maybe the download should take place when transforming the `sdist` into `wheel` then?

Could you please open a GitHub discussion in pypa/setuptools with a minimal reproducible example of what you want to achieve + more details? It does not have to be the same as your real project (and actually it would be better if it is just a dummy that capture the essential parts). I think that would make things easier to understand and talk about (unfortunately I don't have the privileges in this repo to transfer the ticket to setuptools).

**Comment by Earammak** [comment]
> If you need to download a file for each platform when creating the wheel, maybe the download should take place when transforming the `sdist` into `wheel` then?
> Ideally it will be fine when it gets included in source distribution and corresponding wheel files are built. 
I'm not sure, how to install a package when we don't have corresponding wheel package.
> Could you please open a GitHub discussion in pypa/setuptools with a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of what you want to achieve + more details? It does not have to be the same as your real project (and actually it would be better if it is just a dummy that capture the essential parts and omit all the parts that are not necessary). I think that would make things easier to understand and talk about (unfortunately I don't have the privileges in this repo to transfer the ticket to setuptools).

> ok i'll discuss with setuptools package. 

Thank you so much for sharing the information.
