### ISSUE TITLE
Can I specify local source for "build-system.requires"?

### ISSUE THREAD

**Issue by hellozyemlya** [pypa/build#685]
Is it possible to specify folder with pyproject.toml or setup.py with additions for build system?

**Comment by henryiii** [comment]
Yes, some examples are at https://setuptools.pypa.io/en/latest/build_meta.html#dynamic-build-dependencies-and-other-build-meta-tweaks and https://scikit-build.readthedocs.io/en/latest/usage.html#adding-cmake-as-building-requirement-only-if-not-installed-or-too-low-a-version. You have to wrap the hooks the backend provides.
