### ISSUE TITLE
Command does not make sure the output directory exists

### ISSUE THREAD

**Issue by uranusjr** [pypa/build#69]
And it crashes when it doesn’t. This is particularly problematic since the default output directory (``$PWD/dist``) is usually absent in a newly checked out repository.

This works:

```
$ python -m build -s -o .
```

But this fails if ``./dist`` does not exist, with a cryptic message:

```
$ python -m build -s
Traceback (most recent call last):
  File "lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
NotADirectoryError: [WinError 267] The directory name is invalid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "build\__init__.py", line 143, in build
    raise BuildBackendException('Backend operation failed: {}'.format(e))
build.BuildBackendException: Backend operation failed: [WinError 267] The directory name is invalid

ERROR Backend operation failed: [WinError 267] The directory name is invalid
```

**Comment by FFY00** [comment]
Can you confirm this is working on `master`?

**Comment by uranusjr** [comment]
It works if I provide an absolute path to `-o`, but creates if the path is relative; the directory is created at the wrong location.

```
$ python -m build ./example-project/ -s -o output-directory
Traceback (most recent call last):
...
FileNotFoundError: [Errno 2] No such file or directory: '/.../example-project/output-directory/my_package-2.tar.gz'
...
$ ls
example-project
output-directory
```

**Comment by FFY00** [comment]
This should be fixed now. Feel free to reopen if you are still having issues.

**Comment by uranusjr** [comment]
I’m still running into problems.

(Start in the root directory of a valid project.)

```
$ cd (project-root)
$ mkdir foo
$ cd foo  # Now we are in (project-root)/foo
$ python -m build .. -s
...
$ ls
dist
$ ls dist
pkg-1.tar.gz
```

The distribution got created in the nested `(project-root)/foo/dist` (i.e. `dist` resolved against the working directory) instead of `(project-root)/dist` (`dist` resolved against the project root).

However:

```
$ cd (project-root)/foo
$ python -m build .. -s -d bar
$ ls dist
bar
$ ls bar  # Empty!
$ ls ..
bar   ...(other project files)
```

A custom `-d` value is resolved against the project root, instead of the working directory.

The behaviour should be entirely the other way around. The default `dist` directory should be located in the project root no matter what the current working directory is; a custom destination directory should be located relative to the current working directory, no matter where the project is.

**Comment by layday** [comment]
#161 made `outdir` default to `dist` in the project root.  I am not able to repro the second issue with the `outdir` being created relative to the `srcdir`.

**Comment by FFY00** [comment]
Closing this for now, feel free to reopen.
