### ISSUE TITLE
Curly brackets in pathname on VMware virtualenv mess up build process

### ISSUE THREAD

**Issue by veenstrajelmer** [pypa/build#703]
When using `python -m build` on a VMware virtual machine the f-string solving is caught off guard since the path contains curly brackets: `"C:\SnapVolumesTemp\MountPoints\{45c63495-0000-0000-0000-100000000000}\{79DE0690-9470-4166-B9EE-4548DC416BBD}\SVROOT\Users\[...]"`. I think we can agree that this is an improper and inconvenient pathname, but I wondered if it can be solved in build anyway.

```
Traceback (most recent call last):
  File "C:\SnapVolumesTemp\MountPoints\{45c63495-0000-0000-0000-100000000000}\{79DE0690-9470-4166-B9EE-4548DC416BBD}\SVROOT\Users\veenstra\AppData\Local\Temp\build-env-ls6du26j\Lib\site-packages\setuptools\_distutils\util.py", line 212, in subst_vars
    return _subst_compat(s).format_map(lookup)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: '45c63495-0000-0000-0000-100000000000'

```

**Comment by layday** [comment]
This is not a build issue. The error is raised by setuptools.

**Comment by veenstrajelmer** [comment]
Sorry, I was not paying attention. I have created a new issue at setuptools. Thanks for the quick response.
