### ISSUE TITLE
[docs][infra] Set up a pypa.io subdomain for docs?

### ISSUE THREAD

**Issue by webknjaz** [pypa/build#715]
$sbj. It's essentially the same as https://github.com/pypa/pipx/issues/1058.
Any objections?

It would be kinda cool if the domain would read `build.pypa.io`, don't you think?

**Comment by layday** [comment]
Sure - what needs to happen?

**Comment by webknjaz** [comment]
1. Agree among the maintainers
2. Tag Ee to make the DNS changes
3. Add the domain to the RTD settings

**Comment by henryiii** [comment]
I’ve wanted this for a long time, but @FFY00 is the only owner on RtD.

**Comment by FFY00** [comment]
Sorry for the delay, I took a break and am only now coming back to normality. I have added Henry to RTD, he can add the rest of the maintainers.

**Comment by webknjaz** [comment]
@ewdurbin could you point `build.pypa.io` to RTD?

**Comment by ewdurbin** [comment]
Done.

**Comment by webknjaz** [comment]
Thanks!

@henryiii what's left now is for you to paste the domain @ https://readthedocs.org/dashboard/pypa-build/domains/ and then, update it in the sidebar of the repo front page (and somewhere in the package metadata, and readme too, I suppose).
