### ISSUE TITLE
no such option: --python

### ISSUE THREAD

**Issue by oeway** [pypa/build#745]
Hi, the latest upgrade to `1.1.0` causes build error, which saids `no such option: --python`.

Here is an example:
https://github.com/bioimage-io/bioimageio-chatbot/actions/runs/8099920811/job/22136780917#step:4:91

If I pin `build==1.0.3`, then [it works](https://github.com/bioimage-io/bioimageio-chatbot/actions/runs/8099998582/job/22137021599#step:4:5). I also tried to upgrade pip, but it didn't help.

**Comment by cr1901** [comment]
https://build.pypa.io/en/stable/changelog.html#id1

> Use external pip if available instead of installing, speeds up environment setup with virtualenv slightly and venv significantly. (PR [#736](https://github.com/pypa/build/pull/736))

Probably related? Interesting that upgrading pip didn't help though...

**Comment by layday** [comment]
That would be because we're invoking Python with the `-I` flag which makes it ignore user site packages.  In addition, the minimum version of pip is wrong.

**Comment by layday** [comment]
#746

**Comment by henryiii** [comment]
I've yanked 1.1.0 until we fix this.

**Comment by henryiii** [comment]
1.1.1 is out.
