### ISSUE TITLE
Terminal size error with 1.2.0

### ISSUE THREAD

**Issue by santhonisz** [pypa/build#760]
Hi there,

It appears that the changes added in https://github.com/pypa/build/pull/749 have the potential to break usage of `build` when the terminal size cannot be determined.

In our CI pipeline on Buildkite, we call `python -m build -w` on a `python:3.8` Docker container. Since the release of `build==1.2.0` this is failing with the following error:

![image](https://github.com/pypa/build/assets/29723862/d773ade6-15d2-453c-a758-882e1d2aaa5b)

The call to `shutil.get_terminal_size().columns` is evidently returning zero in this case and, as per the [docs](https://docs.python.org/3/library/shutil.html#shutil.get_terminal_size), when using Python < 3.11 the default `fallback` value will not be used.

> Changed in version 3.11: The fallback values are also used if [os.get_terminal_size()](https://docs.python.org/3/library/os.html#os.get_terminal_size) returns zeroes.

While it is possible to work around the issue in our pipeline, I think this scenario should be better handled by `build`.

**Comment by henryiii** [comment]
I've yanked 1.2.0 and will try to get a 1.2.1 out soon.

**Comment by henryiii** [comment]
1.2.1 is out. PyPI was blocking all uploads for a bit, but it's out now.
