### ISSUE TITLE
Behaviour change on hyphen in package names with build 1.2.x?

### ISSUE THREAD

**Issue by HubTou** [pypa/build#770]
I think I noticed a behaviour change with build releases 1.2.x.

It seems that hyphen in package names are now replaced with underscore in the .tar.gz distribution files.

I documented this in [another PR](https://github.com/pypi/warehouse/issues/15770).

**Comment by layday** [comment]
This is correct according to the [sdist spec](https://packaging.python.org/en/latest/specifications/source-distribution-format/#source-distribution-file-name) - filename segments are separated by hyphens and dist names are normalised, replacing hyphens with underscores.  Assuming you are using setuptools, the change you are observing is https://github.com/pypa/setuptools/issues/3593, and is unrelated to build.
