### ISSUE TITLE
setup.py downloads missing from 1.1.0+

### ISSUE THREAD

**Issue by JaimeHolland** [pypa/build#791]
Hi, I ran into a problem when trying to build the [amazon_kclpy](https://github.com/awslabs/amazon-kinesis-client-python/tree/master) package 

The [setup.py ](https://github.com/awslabs/amazon-kinesis-client-python/blob/master/setup.py#L195)file for this library downloads some JARs from Maven (and adds them to the wheel) that are required to get an application running.

In `build` version "1.0.3" this works.  In version "1.1.0" onwards, the JARs are no longer being added to the wheel.  I was wondering if this is because of a missing wheels dependency, i.e. https://github.com/pypa/build/pull/716, but I may be wrong.

Do you have any advice about why this has happened, whether there is a workaround, or if the amazon_kclpy project needs to be brought up to date in some way?

**Comment by JamesParrott** [comment]
I think you're wondering exactly on the right lines.  This likely is due to the dependency on `wheel` being removed in 1.10.  Have you tried installing wheel in the build environment you're calling `build` in?

```

try:
    from wheel.bdist_wheel import bdist_wheel


...

except ImportError:
    pass
```

**Comment by henryiii** [comment]
The package is missing a `pyproject.toml` file; it should have one that explicitly mentions the wheel dependency (and setup_requires can be retired). Wheel will be present when building wheels, but not when making the SDist, I assume it's because you are going SDist -> Wheel?

You could try going directly to wheel with `pipx run build --wheel` (or however you use build), and I think that might still work.

By the way, the next release of setuptools will integrate the bdist_wheel command and wheel will start producing warnings if used. So this is likely about to stop working anyway.

**Comment by henryiii** [comment]
> have you tried installing wheel in the build environment you're calling build in?

You would also need to use `--no-isolation` if going this path.

**Comment by dimbleby** [comment]
cf https://github.com/awslabs/amazon-kinesis-client-python/issues/252

**Comment by JaimeHolland** [comment]
Thank you. Using `--no-isolation` and installing `setuptools` and `wheel` (and also `pytest-runner`) in the environment did work...

**Comment by JaimeHolland** [comment]
This has solved the mystery for me, although my exact use case is that I am using `build` indirectly - I am actually using `poetry`, and it is the fact that `poetry` has bumped the `build` version which has led to my question.

Since I am not calling `build` directly, is there an environment variable I can set to do the equivalent of the `--no-isolation` switch?

**Comment by JaimeHolland** [comment]
> > have you tried installing wheel in the build environment you're calling build in?
> 
> You would also need to use `--no-isolation` if going this path.

Thank you. Using `--no-isolation` and installing `setuptools` and `wheel` (and also `pytest-runner`) in the environment did work...

This has solved the mystery for me, although my exact use case is that I am using `build` indirectly - I am actually using `poetry`, and it is the fact that `poetry` has bumped the `build` version which has led to my question.

Since I am not calling `build` directly, is there an environment variable I can set to do the equivalent of the `--no-isolation` switch?

**Comment by JaimeHolland** [comment]
> The package is missing a `pyproject.toml` file; it should have one that explicitly mentions the wheel dependency (and setup_requires can be retired). Wheel will be present when building wheels, but not when making the SDist, I assume it's because you are going SDist -> Wheel?
> 
> You could try going directly to wheel with `pipx run build --wheel` (or however you use build), and I think that might still work.
> 
> By the way, the next release of setuptools will integrate the bdist_wheel command and wheel will start producing warnings if used. So this is likely about to stop working anyway.

It seems like there's a lot of change happening in this area of Python which is good.  If this jar-downloading process is considered hacky and bound to stop working at some point anyway, I'll stop trying to fix the behaviour and do something else instead to make sure the files are there when needed.  Thanks.

**Comment by jakeberg** [comment]
@JaimeHolland What was your solution to this? It's hard to believe that this has gone unnoticed since 1.1.0. We are planning on pulling some of the code from setup.py to download the files in our Docker container.

**Comment by henryiii** [comment]
Python 3.11 and earlier tend to pre-install `wheel`. And due to a mistake that is fixed for 3.13, some 3.12 environments include it too. So it likely wasn't really noticed (especially since there's a fallback if wheel is missing). The (temporary) fix is to provide a pyproject.toml that gives the actual requirements. Long-term, this will likely need to be updated for the upcoming changes in setuptools to integrate wheel.

**Comment by JaimeHolland** [comment]
> @JaimeHolland What was your solution to this? It's hard to believe that this has gone unnoticed since 1.1.0. We are planning on pulling some of the code from setup.py to download the files in our Docker container.

Yes, this is basically what I did as a hack until I find a cleaner / more up-to-date solution

**Comment by henryiii** [comment]
Ahh, wheel was removed in 70.1. So I think that's why this suddenly is showing up. 70.1+ won't be installing wheel at all because it's not used.
