### ISSUE TITLE
feature request: `python -m build --wheel --exclude-source-files`

### ISSUE THREAD

**Issue by greyltc** [pypa/build#835]
setuptools has this feature, `--exclude-source-files`, one can use while building eggs that removes source code from the produced package. Is there any such feature in build for wheels? If not, this is a request for integrating that feature naively into the build project.

Here are the setuptools docs on the feature: https://setuptools.pypa.io/en/latest/deprecated/commands.html#bdist-egg-create-a-python-egg-for-the-project

**Comment by layday** [comment]
This would be up to each individual backend to support unless standardised.
