### ISSUE TITLE
passing `--jobs` to maturin doesn't work

### ISSUE THREAD

**Issue by 0-wiz-0** [pypa/build#837]
We're using build as the default build tool for packaging Python modules in pkgsrc. So far it's working great, thank you.

Today we noticed that maturin by default uses one compilation job per CPU. We have a centralized variable in pkgsrc that a user can set to decide how many jobs to use in parallel (important if you're building a lot of packages in parallel) so I wanted to pass that through build to maturin.

From the maturin command line docs:
```
# maturin pep517 build-wheel -h
Implementation of build_wheel
...
Compilation Options:
  -j, --jobs <N>                Number of parallel jobs, defaults to # of CPUs
...
```
I tried passing that to maturin using build's `-C` flag, using all kinds of variations:
```
-C-j1
-C-j=1
-C--jobs=1
-C--build-option=--jobs=1
```
leading to a complete command line of
```
/usr/pkg/bin/python3.13 -m build --wheel --skip-dependency-check --no-isolation -C--build-option=--jobs=1
```
but whatever I do, maturin is always called with
```
maturin pep517 build-wheel -i /usr/pkg/bin/python3.11 --compatibility off
``` 

How can I pass `-j1` to maturin's build backend using `build`?

**Comment by 0-wiz-0** [comment]
Ah, in case it matters, my tests were done with building [ruff](https://github.com/astral-sh/ruff) 0.7.3.

**Comment by layday** [comment]
Try `-build-args=--jobs=1`.

**Comment by 0-wiz-0** [comment]
Thank you, that seems to work. Could this be added to the documentation as an example, please?

**Comment by layday** [comment]
`build-args` is maturin-specific. I discovered it from reading the [source code](https://github.com/PyO3/maturin/blob/ae059a3dca24ceb9b18f4bcdf627187e79fec00c/maturin/__init__.py#L37); it doesn't appear to be documented.
