### ISSUE TITLE
Rename `IsolatedEnvironment.install` to be `IsolatedEnvironment.install_with_pip` instead?

### ISSUE THREAD

**Issue by pradyunsg** [pypa/build#96]
https://github.com/FFY00/python-build/blob/2b18f118cd3021f61613dc3381230ffaa32fad16/src/build/env.py#L160

It's more explicit that way, and, yes, I know this is a nit-pick. 😅

**Comment by FFY00** [comment]
This is supposed to be agnostic. The default implementation uses pip right now, but *could* change in the future. I guess the implementation might have some side-effects, like perhaps accepting `-e path`(?), so I think we should clarify it receives [PEP 508](https://www.python.org/dev/peps/pep-0508/) dependencies in the documentation.

If you want to use anaconda for eg. you should subclass `IsolatedEnvironment` and override `install`.

**Comment by pradyunsg** [comment]
> I guess the implementation might have some side-effects, like perhaps accepting `-e path`(?), so I think we should clarify it receives [PEP 508](https://www.python.org/dev/peps/pep-0508/) dependencies in the documentation.

TBH, documentation won't be enough defense here, because [Hyrum's Law](https://www.hyrumslaw.com/) applies to Python packaging. :P

**Comment by FFY00** [comment]
In Python, most things are accessible and can be modified. If you do not follow standard practices and ignore documentation you have no guarantees. If we go by, everything that I can access can be used, the only way to ensure compatibility would be to keep the same code. When you change code, you change behavior :cowboy_hat_face:

Of course everything there could be used, but I don't guarantee compatibility. If you want to do something outside the documentation, you are free to, but please pin the dependency version. If you don't, don't @ me when it breaks :shrug:

At least that is my POV.

**Comment by gaborbernat** [comment]
I think for now it's an implementation detail. And for now, we can keep it as such. We can reopen later if must.
